// -------------------------------------------------------------
// 
// File Name: hdl_project_verilog\hdlsrc\project_detect\Compute_Power.v
// Created: 2021-02-13 17:18:24
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Compute_Power
// Source Path: project_detect/Pulse Detector/Compute Power
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Compute_Power
          (data_in_re,
           data_in_im,
           data_out);


  input   signed [39:0] data_in_re;  // sfix40_En37
  input   signed [39:0] data_in_im;  // sfix40_En37
  output  signed [17:0] data_out;  // sfix18_En11


  wire signed [17:0] Data_Type_Conversion1_out1_re;  // sfix18_En15
  wire signed [17:0] Data_Type_Conversion1_out1_im;  // sfix18_En15
  wire signed [35:0] Product_out1;  // sfix36_En30
  wire signed [35:0] Product1_out1;  // sfix36_En30
  wire signed [36:0] Add_add_cast;  // sfix37_En30
  wire signed [36:0] Add_add_cast_1;  // sfix37_En30
  wire signed [36:0] Add_out1;  // sfix37_En30
  wire signed [17:0] Data_Type_Conversion_out1;  // sfix18_En11


  assign Data_Type_Conversion1_out1_re = data_in_re[39:22];
  assign Data_Type_Conversion1_out1_im = data_in_im[39:22];



  assign Product_out1 = Data_Type_Conversion1_out1_re * Data_Type_Conversion1_out1_re;



  assign Product1_out1 = Data_Type_Conversion1_out1_im * Data_Type_Conversion1_out1_im;



  assign Add_add_cast = {Product_out1[35], Product_out1};
  assign Add_add_cast_1 = {Product1_out1[35], Product1_out1};
  assign Add_out1 = Add_add_cast + Add_add_cast_1;



  assign Data_Type_Conversion_out1 = Add_out1[36:19];



  assign data_out = Data_Type_Conversion_out1;

endmodule  // Compute_Power

