// -------------------------------------------------------------
// 
// File Name: hdl_project_verilog\hdlsrc\project_detect\FilterBank.v
// Created: 2021-02-13 17:18:24
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterBank
// Source Path: project_detect/Pulse Detector/Discrete FIR Filter HDL Optimized/FilterBank
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterBank
          (clk,
           reset,
           enb,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  output  signed [39:0] dataOut_re;  // sfix40_En37
  output  signed [39:0] dataOut_im;  // sfix40_En37
  output  validOut;


  wire syncReset;
  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En14
  wire signed [16:0] dinReg_cast_0_re;  // sfix17_En14
  reg signed [16:0] dinReg2_0_re;  // sfix17_En14
  wire signed [18:0] CoefOutP_0;  // sfix19_En23
  wire signed [18:0] CoefOutP_1;  // sfix19_En23
  wire signed [18:0] CoefOutP_2;  // sfix19_En23
  wire signed [18:0] CoefOutP_3;  // sfix19_En23
  wire signed [18:0] CoefOutP_4;  // sfix19_En23
  wire signed [18:0] CoefOutP_5;  // sfix19_En23
  wire signed [18:0] CoefOutP_6;  // sfix19_En23
  wire signed [18:0] CoefOutP_7;  // sfix19_En23
  wire signed [18:0] CoefOutP_8;  // sfix19_En23
  wire signed [18:0] CoefOutP_9;  // sfix19_En23
  wire signed [18:0] CoefOutP_10;  // sfix19_En23
  wire signed [18:0] CoefOutP_11;  // sfix19_En23
  wire signed [18:0] CoefOutP_12;  // sfix19_En23
  wire signed [18:0] CoefOutP_13;  // sfix19_En23
  wire signed [18:0] CoefOutP_14;  // sfix19_En23
  wire signed [18:0] CoefOutP_15;  // sfix19_En23
  wire signed [18:0] CoefOutP_16;  // sfix19_En23
  wire signed [18:0] CoefOutP_17;  // sfix19_En23
  wire signed [18:0] CoefOutP_18;  // sfix19_En23
  wire signed [18:0] CoefOutP_19;  // sfix19_En23
  wire signed [18:0] CoefOutP_20;  // sfix19_En23
  wire signed [18:0] CoefOutP_21;  // sfix19_En23
  wire signed [18:0] CoefOutP_22;  // sfix19_En23
  wire signed [18:0] CoefOutP_23;  // sfix19_En23
  wire signed [18:0] CoefOutP_24;  // sfix19_En23
  wire signed [18:0] CoefOutP_25;  // sfix19_En23
  wire signed [18:0] CoefOutP_26;  // sfix19_En23
  wire signed [18:0] CoefOutP_27;  // sfix19_En23
  wire signed [18:0] CoefOutP_28;  // sfix19_En23
  wire signed [18:0] CoefOutP_29;  // sfix19_En23
  wire signed [18:0] CoefOutP_30;  // sfix19_En23
  wire signed [18:0] CoefOutP_31;  // sfix19_En23
  wire signed [18:0] CoefOutP_32;  // sfix19_En23
  wire signed [18:0] CoefOutP_33;  // sfix19_En23
  wire signed [18:0] CoefOutP_34;  // sfix19_En23
  wire signed [18:0] CoefOutP_35;  // sfix19_En23
  wire signed [18:0] CoefOutP_36;  // sfix19_En23
  wire signed [18:0] CoefOutP_37;  // sfix19_En23
  wire signed [18:0] CoefOutP_38;  // sfix19_En23
  wire signed [18:0] CoefOutP_39;  // sfix19_En23
  wire signed [18:0] CoefOutP_40;  // sfix19_En23
  wire signed [18:0] CoefOutP_41;  // sfix19_En23
  wire signed [18:0] CoefOutP_42;  // sfix19_En23
  wire signed [18:0] CoefOutP_43;  // sfix19_En23
  wire signed [18:0] CoefOutP_44;  // sfix19_En23
  wire signed [18:0] CoefOutP_45;  // sfix19_En23
  wire signed [18:0] CoefOutP_46;  // sfix19_En23
  wire signed [18:0] CoefOutP_47;  // sfix19_En23
  wire signed [18:0] CoefOutP_48;  // sfix19_En23
  wire signed [18:0] CoefOutP_49;  // sfix19_En23
  wire signed [18:0] CoefOutP_50;  // sfix19_En23
  wire signed [18:0] CoefOutP_51;  // sfix19_En23
  wire signed [18:0] CoefOutP_52;  // sfix19_En23
  wire signed [18:0] CoefOutP_53;  // sfix19_En23
  wire signed [18:0] CoefOutP_54;  // sfix19_En23
  wire signed [18:0] CoefOutP_55;  // sfix19_En23
  wire signed [18:0] CoefOutP_56;  // sfix19_En23
  wire signed [18:0] CoefOutP_57;  // sfix19_En23
  wire signed [18:0] CoefOutP_58;  // sfix19_En23
  wire signed [18:0] CoefOutP_59;  // sfix19_En23
  wire signed [18:0] CoefOutP_60;  // sfix19_En23
  wire signed [18:0] CoefOutP_61;  // sfix19_En23
  wire signed [18:0] CoefOutP_62;  // sfix19_En23
  wire signed [18:0] CoefOutP_63;  // sfix19_En23
  reg  dinReg2Vld;
  wire signed [39:0] dout_1_P;  // sfix40_En37
  wire doutVld;
  reg signed [15:0] dinReg_0_im;  // sfix16_En14
  wire signed [16:0] adder_add_cast;  // sfix17_En14
  wire signed [16:0] adder_add_cast_1;  // sfix17_En14
  wire signed [16:0] dinRealPImag_0;  // sfix17_En14
  reg signed [16:0] dinReg2_0_P;  // sfix17_En14
  wire signed [18:0] CoefOutI_0;  // sfix19_En23
  wire signed [18:0] CoefOutI_1;  // sfix19_En23
  wire signed [18:0] CoefOutI_2;  // sfix19_En23
  wire signed [18:0] CoefOutI_3;  // sfix19_En23
  wire signed [18:0] CoefOutI_4;  // sfix19_En23
  wire signed [18:0] CoefOutI_5;  // sfix19_En23
  wire signed [18:0] CoefOutI_6;  // sfix19_En23
  wire signed [18:0] CoefOutI_7;  // sfix19_En23
  wire signed [18:0] CoefOutI_8;  // sfix19_En23
  wire signed [18:0] CoefOutI_9;  // sfix19_En23
  wire signed [18:0] CoefOutI_10;  // sfix19_En23
  wire signed [18:0] CoefOutI_11;  // sfix19_En23
  wire signed [18:0] CoefOutI_12;  // sfix19_En23
  wire signed [18:0] CoefOutI_13;  // sfix19_En23
  wire signed [18:0] CoefOutI_14;  // sfix19_En23
  wire signed [18:0] CoefOutI_15;  // sfix19_En23
  wire signed [18:0] CoefOutI_16;  // sfix19_En23
  wire signed [18:0] CoefOutI_17;  // sfix19_En23
  wire signed [18:0] CoefOutI_18;  // sfix19_En23
  wire signed [18:0] CoefOutI_19;  // sfix19_En23
  wire signed [18:0] CoefOutI_20;  // sfix19_En23
  wire signed [18:0] CoefOutI_21;  // sfix19_En23
  wire signed [18:0] CoefOutI_22;  // sfix19_En23
  wire signed [18:0] CoefOutI_23;  // sfix19_En23
  wire signed [18:0] CoefOutI_24;  // sfix19_En23
  wire signed [18:0] CoefOutI_25;  // sfix19_En23
  wire signed [18:0] CoefOutI_26;  // sfix19_En23
  wire signed [18:0] CoefOutI_27;  // sfix19_En23
  wire signed [18:0] CoefOutI_28;  // sfix19_En23
  wire signed [18:0] CoefOutI_29;  // sfix19_En23
  wire signed [18:0] CoefOutI_30;  // sfix19_En23
  wire signed [18:0] CoefOutI_31;  // sfix19_En23
  wire signed [18:0] CoefOutI_32;  // sfix19_En23
  wire signed [18:0] CoefOutI_33;  // sfix19_En23
  wire signed [18:0] CoefOutI_34;  // sfix19_En23
  wire signed [18:0] CoefOutI_35;  // sfix19_En23
  wire signed [18:0] CoefOutI_36;  // sfix19_En23
  wire signed [18:0] CoefOutI_37;  // sfix19_En23
  wire signed [18:0] CoefOutI_38;  // sfix19_En23
  wire signed [18:0] CoefOutI_39;  // sfix19_En23
  wire signed [18:0] CoefOutI_40;  // sfix19_En23
  wire signed [18:0] CoefOutI_41;  // sfix19_En23
  wire signed [18:0] CoefOutI_42;  // sfix19_En23
  wire signed [18:0] CoefOutI_43;  // sfix19_En23
  wire signed [18:0] CoefOutI_44;  // sfix19_En23
  wire signed [18:0] CoefOutI_45;  // sfix19_En23
  wire signed [18:0] CoefOutI_46;  // sfix19_En23
  wire signed [18:0] CoefOutI_47;  // sfix19_En23
  wire signed [18:0] CoefOutI_48;  // sfix19_En23
  wire signed [18:0] CoefOutI_49;  // sfix19_En23
  wire signed [18:0] CoefOutI_50;  // sfix19_En23
  wire signed [18:0] CoefOutI_51;  // sfix19_En23
  wire signed [18:0] CoefOutI_52;  // sfix19_En23
  wire signed [18:0] CoefOutI_53;  // sfix19_En23
  wire signed [18:0] CoefOutI_54;  // sfix19_En23
  wire signed [18:0] CoefOutI_55;  // sfix19_En23
  wire signed [18:0] CoefOutI_56;  // sfix19_En23
  wire signed [18:0] CoefOutI_57;  // sfix19_En23
  wire signed [18:0] CoefOutI_58;  // sfix19_En23
  wire signed [18:0] CoefOutI_59;  // sfix19_En23
  wire signed [18:0] CoefOutI_60;  // sfix19_En23
  wire signed [18:0] CoefOutI_61;  // sfix19_En23
  wire signed [18:0] CoefOutI_62;  // sfix19_En23
  wire signed [18:0] CoefOutI_63;  // sfix19_En23
  wire signed [39:0] dout_1_I;  // sfix40_En37
  wire doutVld_I;
  wire signed [40:0] subtractor_sub_cast;  // sfix41_En37
  wire signed [40:0] subtractor_sub_cast_1;  // sfix41_En37
  wire signed [40:0] dout_1_r;  // sfix41_En37
  wire signed [39:0] dout_1_cast_r;  // sfix40_En37
  reg signed [39:0] dout_1_re;  // sfix40_En37
  wire signed [16:0] dinReg2_cast_0_im;  // sfix17_En14
  reg signed [16:0] dinReg2_0_im;  // sfix17_En14
  wire signed [18:0] CoefOutS_0;  // sfix19_En23
  wire signed [18:0] CoefOutS_1;  // sfix19_En23
  wire signed [18:0] CoefOutS_2;  // sfix19_En23
  wire signed [18:0] CoefOutS_3;  // sfix19_En23
  wire signed [18:0] CoefOutS_4;  // sfix19_En23
  wire signed [18:0] CoefOutS_5;  // sfix19_En23
  wire signed [18:0] CoefOutS_6;  // sfix19_En23
  wire signed [18:0] CoefOutS_7;  // sfix19_En23
  wire signed [18:0] CoefOutS_8;  // sfix19_En23
  wire signed [18:0] CoefOutS_9;  // sfix19_En23
  wire signed [18:0] CoefOutS_10;  // sfix19_En23
  wire signed [18:0] CoefOutS_11;  // sfix19_En23
  wire signed [18:0] CoefOutS_12;  // sfix19_En23
  wire signed [18:0] CoefOutS_13;  // sfix19_En23
  wire signed [18:0] CoefOutS_14;  // sfix19_En23
  wire signed [18:0] CoefOutS_15;  // sfix19_En23
  wire signed [18:0] CoefOutS_16;  // sfix19_En23
  wire signed [18:0] CoefOutS_17;  // sfix19_En23
  wire signed [18:0] CoefOutS_18;  // sfix19_En23
  wire signed [18:0] CoefOutS_19;  // sfix19_En23
  wire signed [18:0] CoefOutS_20;  // sfix19_En23
  wire signed [18:0] CoefOutS_21;  // sfix19_En23
  wire signed [18:0] CoefOutS_22;  // sfix19_En23
  wire signed [18:0] CoefOutS_23;  // sfix19_En23
  wire signed [18:0] CoefOutS_24;  // sfix19_En23
  wire signed [18:0] CoefOutS_25;  // sfix19_En23
  wire signed [18:0] CoefOutS_26;  // sfix19_En23
  wire signed [18:0] CoefOutS_27;  // sfix19_En23
  wire signed [18:0] CoefOutS_28;  // sfix19_En23
  wire signed [18:0] CoefOutS_29;  // sfix19_En23
  wire signed [18:0] CoefOutS_30;  // sfix19_En23
  wire signed [18:0] CoefOutS_31;  // sfix19_En23
  wire signed [18:0] CoefOutS_32;  // sfix19_En23
  wire signed [18:0] CoefOutS_33;  // sfix19_En23
  wire signed [18:0] CoefOutS_34;  // sfix19_En23
  wire signed [18:0] CoefOutS_35;  // sfix19_En23
  wire signed [18:0] CoefOutS_36;  // sfix19_En23
  wire signed [18:0] CoefOutS_37;  // sfix19_En23
  wire signed [18:0] CoefOutS_38;  // sfix19_En23
  wire signed [18:0] CoefOutS_39;  // sfix19_En23
  wire signed [18:0] CoefOutS_40;  // sfix19_En23
  wire signed [18:0] CoefOutS_41;  // sfix19_En23
  wire signed [18:0] CoefOutS_42;  // sfix19_En23
  wire signed [18:0] CoefOutS_43;  // sfix19_En23
  wire signed [18:0] CoefOutS_44;  // sfix19_En23
  wire signed [18:0] CoefOutS_45;  // sfix19_En23
  wire signed [18:0] CoefOutS_46;  // sfix19_En23
  wire signed [18:0] CoefOutS_47;  // sfix19_En23
  wire signed [18:0] CoefOutS_48;  // sfix19_En23
  wire signed [18:0] CoefOutS_49;  // sfix19_En23
  wire signed [18:0] CoefOutS_50;  // sfix19_En23
  wire signed [18:0] CoefOutS_51;  // sfix19_En23
  wire signed [18:0] CoefOutS_52;  // sfix19_En23
  wire signed [18:0] CoefOutS_53;  // sfix19_En23
  wire signed [18:0] CoefOutS_54;  // sfix19_En23
  wire signed [18:0] CoefOutS_55;  // sfix19_En23
  wire signed [18:0] CoefOutS_56;  // sfix19_En23
  wire signed [18:0] CoefOutS_57;  // sfix19_En23
  wire signed [18:0] CoefOutS_58;  // sfix19_En23
  wire signed [18:0] CoefOutS_59;  // sfix19_En23
  wire signed [18:0] CoefOutS_60;  // sfix19_En23
  wire signed [18:0] CoefOutS_61;  // sfix19_En23
  wire signed [18:0] CoefOutS_62;  // sfix19_En23
  wire signed [18:0] CoefOutS_63;  // sfix19_En23
  wire signed [39:0] dout_1_M;  // sfix40_En37
  wire doutVld_M;
  wire signed [40:0] adder_add_cast_2;  // sfix41_En37
  wire signed [40:0] adder_add_cast_3;  // sfix41_En37
  wire signed [40:0] dout_1_i_1;  // sfix41_En37
  wire signed [39:0] dout_1_cast_i;  // sfix40_En37
  reg signed [39:0] dout_1_im;  // sfix40_En37
  reg  doutVldReg;


  assign syncReset = 1'b0;



  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn_re;
            end
          end
        end
      end
    end



  assign dinReg_cast_0_re = {dinReg_0_re[15], dinReg_0_re};



  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinReg2_0_re <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 17'sb00000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_cast_0_re;
            end
          end
        end
      end
    end



  FilterCoef u_CoefTableP_1 (.CoefOutP_0(CoefOutP_0),  // sfix19_En23
                             .CoefOutP_1(CoefOutP_1),  // sfix19_En23
                             .CoefOutP_2(CoefOutP_2),  // sfix19_En23
                             .CoefOutP_3(CoefOutP_3),  // sfix19_En23
                             .CoefOutP_4(CoefOutP_4),  // sfix19_En23
                             .CoefOutP_5(CoefOutP_5),  // sfix19_En23
                             .CoefOutP_6(CoefOutP_6),  // sfix19_En23
                             .CoefOutP_7(CoefOutP_7),  // sfix19_En23
                             .CoefOutP_8(CoefOutP_8),  // sfix19_En23
                             .CoefOutP_9(CoefOutP_9),  // sfix19_En23
                             .CoefOutP_10(CoefOutP_10),  // sfix19_En23
                             .CoefOutP_11(CoefOutP_11),  // sfix19_En23
                             .CoefOutP_12(CoefOutP_12),  // sfix19_En23
                             .CoefOutP_13(CoefOutP_13),  // sfix19_En23
                             .CoefOutP_14(CoefOutP_14),  // sfix19_En23
                             .CoefOutP_15(CoefOutP_15),  // sfix19_En23
                             .CoefOutP_16(CoefOutP_16),  // sfix19_En23
                             .CoefOutP_17(CoefOutP_17),  // sfix19_En23
                             .CoefOutP_18(CoefOutP_18),  // sfix19_En23
                             .CoefOutP_19(CoefOutP_19),  // sfix19_En23
                             .CoefOutP_20(CoefOutP_20),  // sfix19_En23
                             .CoefOutP_21(CoefOutP_21),  // sfix19_En23
                             .CoefOutP_22(CoefOutP_22),  // sfix19_En23
                             .CoefOutP_23(CoefOutP_23),  // sfix19_En23
                             .CoefOutP_24(CoefOutP_24),  // sfix19_En23
                             .CoefOutP_25(CoefOutP_25),  // sfix19_En23
                             .CoefOutP_26(CoefOutP_26),  // sfix19_En23
                             .CoefOutP_27(CoefOutP_27),  // sfix19_En23
                             .CoefOutP_28(CoefOutP_28),  // sfix19_En23
                             .CoefOutP_29(CoefOutP_29),  // sfix19_En23
                             .CoefOutP_30(CoefOutP_30),  // sfix19_En23
                             .CoefOutP_31(CoefOutP_31),  // sfix19_En23
                             .CoefOutP_32(CoefOutP_32),  // sfix19_En23
                             .CoefOutP_33(CoefOutP_33),  // sfix19_En23
                             .CoefOutP_34(CoefOutP_34),  // sfix19_En23
                             .CoefOutP_35(CoefOutP_35),  // sfix19_En23
                             .CoefOutP_36(CoefOutP_36),  // sfix19_En23
                             .CoefOutP_37(CoefOutP_37),  // sfix19_En23
                             .CoefOutP_38(CoefOutP_38),  // sfix19_En23
                             .CoefOutP_39(CoefOutP_39),  // sfix19_En23
                             .CoefOutP_40(CoefOutP_40),  // sfix19_En23
                             .CoefOutP_41(CoefOutP_41),  // sfix19_En23
                             .CoefOutP_42(CoefOutP_42),  // sfix19_En23
                             .CoefOutP_43(CoefOutP_43),  // sfix19_En23
                             .CoefOutP_44(CoefOutP_44),  // sfix19_En23
                             .CoefOutP_45(CoefOutP_45),  // sfix19_En23
                             .CoefOutP_46(CoefOutP_46),  // sfix19_En23
                             .CoefOutP_47(CoefOutP_47),  // sfix19_En23
                             .CoefOutP_48(CoefOutP_48),  // sfix19_En23
                             .CoefOutP_49(CoefOutP_49),  // sfix19_En23
                             .CoefOutP_50(CoefOutP_50),  // sfix19_En23
                             .CoefOutP_51(CoefOutP_51),  // sfix19_En23
                             .CoefOutP_52(CoefOutP_52),  // sfix19_En23
                             .CoefOutP_53(CoefOutP_53),  // sfix19_En23
                             .CoefOutP_54(CoefOutP_54),  // sfix19_En23
                             .CoefOutP_55(CoefOutP_55),  // sfix19_En23
                             .CoefOutP_56(CoefOutP_56),  // sfix19_En23
                             .CoefOutP_57(CoefOutP_57),  // sfix19_En23
                             .CoefOutP_58(CoefOutP_58),  // sfix19_En23
                             .CoefOutP_59(CoefOutP_59),  // sfix19_En23
                             .CoefOutP_60(CoefOutP_60),  // sfix19_En23
                             .CoefOutP_61(CoefOutP_61),  // sfix19_En23
                             .CoefOutP_62(CoefOutP_62),  // sfix19_En23
                             .CoefOutP_63(CoefOutP_63)  // sfix19_En23
                             );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end



  subFilter u_subFilter_1_reP (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .dinReg2_0_re(dinReg2_0_re),  // sfix17_En14
                               .coefIn_0(CoefOutP_0),  // sfix19_En23
                               .coefIn_1(CoefOutP_1),  // sfix19_En23
                               .coefIn_2(CoefOutP_2),  // sfix19_En23
                               .coefIn_3(CoefOutP_3),  // sfix19_En23
                               .coefIn_4(CoefOutP_4),  // sfix19_En23
                               .coefIn_5(CoefOutP_5),  // sfix19_En23
                               .coefIn_6(CoefOutP_6),  // sfix19_En23
                               .coefIn_7(CoefOutP_7),  // sfix19_En23
                               .coefIn_8(CoefOutP_8),  // sfix19_En23
                               .coefIn_9(CoefOutP_9),  // sfix19_En23
                               .coefIn_10(CoefOutP_10),  // sfix19_En23
                               .coefIn_11(CoefOutP_11),  // sfix19_En23
                               .coefIn_12(CoefOutP_12),  // sfix19_En23
                               .coefIn_13(CoefOutP_13),  // sfix19_En23
                               .coefIn_14(CoefOutP_14),  // sfix19_En23
                               .coefIn_15(CoefOutP_15),  // sfix19_En23
                               .coefIn_16(CoefOutP_16),  // sfix19_En23
                               .coefIn_17(CoefOutP_17),  // sfix19_En23
                               .coefIn_18(CoefOutP_18),  // sfix19_En23
                               .coefIn_19(CoefOutP_19),  // sfix19_En23
                               .coefIn_20(CoefOutP_20),  // sfix19_En23
                               .coefIn_21(CoefOutP_21),  // sfix19_En23
                               .coefIn_22(CoefOutP_22),  // sfix19_En23
                               .coefIn_23(CoefOutP_23),  // sfix19_En23
                               .coefIn_24(CoefOutP_24),  // sfix19_En23
                               .coefIn_25(CoefOutP_25),  // sfix19_En23
                               .coefIn_26(CoefOutP_26),  // sfix19_En23
                               .coefIn_27(CoefOutP_27),  // sfix19_En23
                               .coefIn_28(CoefOutP_28),  // sfix19_En23
                               .coefIn_29(CoefOutP_29),  // sfix19_En23
                               .coefIn_30(CoefOutP_30),  // sfix19_En23
                               .coefIn_31(CoefOutP_31),  // sfix19_En23
                               .coefIn_32(CoefOutP_32),  // sfix19_En23
                               .coefIn_33(CoefOutP_33),  // sfix19_En23
                               .coefIn_34(CoefOutP_34),  // sfix19_En23
                               .coefIn_35(CoefOutP_35),  // sfix19_En23
                               .coefIn_36(CoefOutP_36),  // sfix19_En23
                               .coefIn_37(CoefOutP_37),  // sfix19_En23
                               .coefIn_38(CoefOutP_38),  // sfix19_En23
                               .coefIn_39(CoefOutP_39),  // sfix19_En23
                               .coefIn_40(CoefOutP_40),  // sfix19_En23
                               .coefIn_41(CoefOutP_41),  // sfix19_En23
                               .coefIn_42(CoefOutP_42),  // sfix19_En23
                               .coefIn_43(CoefOutP_43),  // sfix19_En23
                               .coefIn_44(CoefOutP_44),  // sfix19_En23
                               .coefIn_45(CoefOutP_45),  // sfix19_En23
                               .coefIn_46(CoefOutP_46),  // sfix19_En23
                               .coefIn_47(CoefOutP_47),  // sfix19_En23
                               .coefIn_48(CoefOutP_48),  // sfix19_En23
                               .coefIn_49(CoefOutP_49),  // sfix19_En23
                               .coefIn_50(CoefOutP_50),  // sfix19_En23
                               .coefIn_51(CoefOutP_51),  // sfix19_En23
                               .coefIn_52(CoefOutP_52),  // sfix19_En23
                               .coefIn_53(CoefOutP_53),  // sfix19_En23
                               .coefIn_54(CoefOutP_54),  // sfix19_En23
                               .coefIn_55(CoefOutP_55),  // sfix19_En23
                               .coefIn_56(CoefOutP_56),  // sfix19_En23
                               .coefIn_57(CoefOutP_57),  // sfix19_En23
                               .coefIn_58(CoefOutP_58),  // sfix19_En23
                               .coefIn_59(CoefOutP_59),  // sfix19_En23
                               .coefIn_60(CoefOutP_60),  // sfix19_En23
                               .coefIn_61(CoefOutP_61),  // sfix19_En23
                               .coefIn_62(CoefOutP_62),  // sfix19_En23
                               .coefIn_63(CoefOutP_63),  // sfix19_En23
                               .dinRegVld(dinReg2Vld),
                               .syncReset(syncReset),
                               .dout_1_re(dout_1_P),  // sfix40_En37
                               .doutVld(doutVld)
                               );

  always @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        dinReg_0_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_im <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_im <= dataIn_im;
            end
          end
        end
      end
    end



  assign adder_add_cast = {dinReg_0_re[15], dinReg_0_re};
  assign adder_add_cast_1 = {dinReg_0_im[15], dinReg_0_im};
  assign dinRealPImag_0 = adder_add_cast + adder_add_cast_1;



  always @(posedge clk)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        dinReg2_0_P <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_P <= 17'sb00000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_P <= dinRealPImag_0;
            end
          end
        end
      end
    end



  FilterCoef_block1 u_CoefTableI_1 (.CoefOutI_0(CoefOutI_0),  // sfix19_En23
                                    .CoefOutI_1(CoefOutI_1),  // sfix19_En23
                                    .CoefOutI_2(CoefOutI_2),  // sfix19_En23
                                    .CoefOutI_3(CoefOutI_3),  // sfix19_En23
                                    .CoefOutI_4(CoefOutI_4),  // sfix19_En23
                                    .CoefOutI_5(CoefOutI_5),  // sfix19_En23
                                    .CoefOutI_6(CoefOutI_6),  // sfix19_En23
                                    .CoefOutI_7(CoefOutI_7),  // sfix19_En23
                                    .CoefOutI_8(CoefOutI_8),  // sfix19_En23
                                    .CoefOutI_9(CoefOutI_9),  // sfix19_En23
                                    .CoefOutI_10(CoefOutI_10),  // sfix19_En23
                                    .CoefOutI_11(CoefOutI_11),  // sfix19_En23
                                    .CoefOutI_12(CoefOutI_12),  // sfix19_En23
                                    .CoefOutI_13(CoefOutI_13),  // sfix19_En23
                                    .CoefOutI_14(CoefOutI_14),  // sfix19_En23
                                    .CoefOutI_15(CoefOutI_15),  // sfix19_En23
                                    .CoefOutI_16(CoefOutI_16),  // sfix19_En23
                                    .CoefOutI_17(CoefOutI_17),  // sfix19_En23
                                    .CoefOutI_18(CoefOutI_18),  // sfix19_En23
                                    .CoefOutI_19(CoefOutI_19),  // sfix19_En23
                                    .CoefOutI_20(CoefOutI_20),  // sfix19_En23
                                    .CoefOutI_21(CoefOutI_21),  // sfix19_En23
                                    .CoefOutI_22(CoefOutI_22),  // sfix19_En23
                                    .CoefOutI_23(CoefOutI_23),  // sfix19_En23
                                    .CoefOutI_24(CoefOutI_24),  // sfix19_En23
                                    .CoefOutI_25(CoefOutI_25),  // sfix19_En23
                                    .CoefOutI_26(CoefOutI_26),  // sfix19_En23
                                    .CoefOutI_27(CoefOutI_27),  // sfix19_En23
                                    .CoefOutI_28(CoefOutI_28),  // sfix19_En23
                                    .CoefOutI_29(CoefOutI_29),  // sfix19_En23
                                    .CoefOutI_30(CoefOutI_30),  // sfix19_En23
                                    .CoefOutI_31(CoefOutI_31),  // sfix19_En23
                                    .CoefOutI_32(CoefOutI_32),  // sfix19_En23
                                    .CoefOutI_33(CoefOutI_33),  // sfix19_En23
                                    .CoefOutI_34(CoefOutI_34),  // sfix19_En23
                                    .CoefOutI_35(CoefOutI_35),  // sfix19_En23
                                    .CoefOutI_36(CoefOutI_36),  // sfix19_En23
                                    .CoefOutI_37(CoefOutI_37),  // sfix19_En23
                                    .CoefOutI_38(CoefOutI_38),  // sfix19_En23
                                    .CoefOutI_39(CoefOutI_39),  // sfix19_En23
                                    .CoefOutI_40(CoefOutI_40),  // sfix19_En23
                                    .CoefOutI_41(CoefOutI_41),  // sfix19_En23
                                    .CoefOutI_42(CoefOutI_42),  // sfix19_En23
                                    .CoefOutI_43(CoefOutI_43),  // sfix19_En23
                                    .CoefOutI_44(CoefOutI_44),  // sfix19_En23
                                    .CoefOutI_45(CoefOutI_45),  // sfix19_En23
                                    .CoefOutI_46(CoefOutI_46),  // sfix19_En23
                                    .CoefOutI_47(CoefOutI_47),  // sfix19_En23
                                    .CoefOutI_48(CoefOutI_48),  // sfix19_En23
                                    .CoefOutI_49(CoefOutI_49),  // sfix19_En23
                                    .CoefOutI_50(CoefOutI_50),  // sfix19_En23
                                    .CoefOutI_51(CoefOutI_51),  // sfix19_En23
                                    .CoefOutI_52(CoefOutI_52),  // sfix19_En23
                                    .CoefOutI_53(CoefOutI_53),  // sfix19_En23
                                    .CoefOutI_54(CoefOutI_54),  // sfix19_En23
                                    .CoefOutI_55(CoefOutI_55),  // sfix19_En23
                                    .CoefOutI_56(CoefOutI_56),  // sfix19_En23
                                    .CoefOutI_57(CoefOutI_57),  // sfix19_En23
                                    .CoefOutI_58(CoefOutI_58),  // sfix19_En23
                                    .CoefOutI_59(CoefOutI_59),  // sfix19_En23
                                    .CoefOutI_60(CoefOutI_60),  // sfix19_En23
                                    .CoefOutI_61(CoefOutI_61),  // sfix19_En23
                                    .CoefOutI_62(CoefOutI_62),  // sfix19_En23
                                    .CoefOutI_63(CoefOutI_63)  // sfix19_En23
                                    );

  subFilter u_subFilter_1_im (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .dinReg2_0_re(dinReg2_0_P),  // sfix17_En14
                              .coefIn_0(CoefOutI_0),  // sfix19_En23
                              .coefIn_1(CoefOutI_1),  // sfix19_En23
                              .coefIn_2(CoefOutI_2),  // sfix19_En23
                              .coefIn_3(CoefOutI_3),  // sfix19_En23
                              .coefIn_4(CoefOutI_4),  // sfix19_En23
                              .coefIn_5(CoefOutI_5),  // sfix19_En23
                              .coefIn_6(CoefOutI_6),  // sfix19_En23
                              .coefIn_7(CoefOutI_7),  // sfix19_En23
                              .coefIn_8(CoefOutI_8),  // sfix19_En23
                              .coefIn_9(CoefOutI_9),  // sfix19_En23
                              .coefIn_10(CoefOutI_10),  // sfix19_En23
                              .coefIn_11(CoefOutI_11),  // sfix19_En23
                              .coefIn_12(CoefOutI_12),  // sfix19_En23
                              .coefIn_13(CoefOutI_13),  // sfix19_En23
                              .coefIn_14(CoefOutI_14),  // sfix19_En23
                              .coefIn_15(CoefOutI_15),  // sfix19_En23
                              .coefIn_16(CoefOutI_16),  // sfix19_En23
                              .coefIn_17(CoefOutI_17),  // sfix19_En23
                              .coefIn_18(CoefOutI_18),  // sfix19_En23
                              .coefIn_19(CoefOutI_19),  // sfix19_En23
                              .coefIn_20(CoefOutI_20),  // sfix19_En23
                              .coefIn_21(CoefOutI_21),  // sfix19_En23
                              .coefIn_22(CoefOutI_22),  // sfix19_En23
                              .coefIn_23(CoefOutI_23),  // sfix19_En23
                              .coefIn_24(CoefOutI_24),  // sfix19_En23
                              .coefIn_25(CoefOutI_25),  // sfix19_En23
                              .coefIn_26(CoefOutI_26),  // sfix19_En23
                              .coefIn_27(CoefOutI_27),  // sfix19_En23
                              .coefIn_28(CoefOutI_28),  // sfix19_En23
                              .coefIn_29(CoefOutI_29),  // sfix19_En23
                              .coefIn_30(CoefOutI_30),  // sfix19_En23
                              .coefIn_31(CoefOutI_31),  // sfix19_En23
                              .coefIn_32(CoefOutI_32),  // sfix19_En23
                              .coefIn_33(CoefOutI_33),  // sfix19_En23
                              .coefIn_34(CoefOutI_34),  // sfix19_En23
                              .coefIn_35(CoefOutI_35),  // sfix19_En23
                              .coefIn_36(CoefOutI_36),  // sfix19_En23
                              .coefIn_37(CoefOutI_37),  // sfix19_En23
                              .coefIn_38(CoefOutI_38),  // sfix19_En23
                              .coefIn_39(CoefOutI_39),  // sfix19_En23
                              .coefIn_40(CoefOutI_40),  // sfix19_En23
                              .coefIn_41(CoefOutI_41),  // sfix19_En23
                              .coefIn_42(CoefOutI_42),  // sfix19_En23
                              .coefIn_43(CoefOutI_43),  // sfix19_En23
                              .coefIn_44(CoefOutI_44),  // sfix19_En23
                              .coefIn_45(CoefOutI_45),  // sfix19_En23
                              .coefIn_46(CoefOutI_46),  // sfix19_En23
                              .coefIn_47(CoefOutI_47),  // sfix19_En23
                              .coefIn_48(CoefOutI_48),  // sfix19_En23
                              .coefIn_49(CoefOutI_49),  // sfix19_En23
                              .coefIn_50(CoefOutI_50),  // sfix19_En23
                              .coefIn_51(CoefOutI_51),  // sfix19_En23
                              .coefIn_52(CoefOutI_52),  // sfix19_En23
                              .coefIn_53(CoefOutI_53),  // sfix19_En23
                              .coefIn_54(CoefOutI_54),  // sfix19_En23
                              .coefIn_55(CoefOutI_55),  // sfix19_En23
                              .coefIn_56(CoefOutI_56),  // sfix19_En23
                              .coefIn_57(CoefOutI_57),  // sfix19_En23
                              .coefIn_58(CoefOutI_58),  // sfix19_En23
                              .coefIn_59(CoefOutI_59),  // sfix19_En23
                              .coefIn_60(CoefOutI_60),  // sfix19_En23
                              .coefIn_61(CoefOutI_61),  // sfix19_En23
                              .coefIn_62(CoefOutI_62),  // sfix19_En23
                              .coefIn_63(CoefOutI_63),  // sfix19_En23
                              .dinRegVld(dinReg2Vld),
                              .syncReset(syncReset),
                              .dout_1_re(dout_1_I),  // sfix40_En37
                              .doutVld(doutVld_I)
                              );

  assign subtractor_sub_cast = {dout_1_P[39], dout_1_P};
  assign subtractor_sub_cast_1 = {dout_1_I[39], dout_1_I};
  assign dout_1_r = subtractor_sub_cast - subtractor_sub_cast_1;



  assign dout_1_cast_r = dout_1_r[39:0];



  always @(posedge clk)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        dout_1_re <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_re <= 40'sh0000000000;
          end
          else begin
            dout_1_re <= dout_1_cast_r;
          end
        end
      end
    end



  assign dataOut_re = dout_1_re;

  assign dinReg2_cast_0_im = {dinReg_0_im[15], dinReg_0_im};



  always @(posedge clk)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        dinReg2_0_im <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_im <= 17'sb00000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_im <= dinReg2_cast_0_im;
            end
          end
        end
      end
    end



  FilterCoef_block u_CoefTableS_1 (.CoefOutS_0(CoefOutS_0),  // sfix19_En23
                                   .CoefOutS_1(CoefOutS_1),  // sfix19_En23
                                   .CoefOutS_2(CoefOutS_2),  // sfix19_En23
                                   .CoefOutS_3(CoefOutS_3),  // sfix19_En23
                                   .CoefOutS_4(CoefOutS_4),  // sfix19_En23
                                   .CoefOutS_5(CoefOutS_5),  // sfix19_En23
                                   .CoefOutS_6(CoefOutS_6),  // sfix19_En23
                                   .CoefOutS_7(CoefOutS_7),  // sfix19_En23
                                   .CoefOutS_8(CoefOutS_8),  // sfix19_En23
                                   .CoefOutS_9(CoefOutS_9),  // sfix19_En23
                                   .CoefOutS_10(CoefOutS_10),  // sfix19_En23
                                   .CoefOutS_11(CoefOutS_11),  // sfix19_En23
                                   .CoefOutS_12(CoefOutS_12),  // sfix19_En23
                                   .CoefOutS_13(CoefOutS_13),  // sfix19_En23
                                   .CoefOutS_14(CoefOutS_14),  // sfix19_En23
                                   .CoefOutS_15(CoefOutS_15),  // sfix19_En23
                                   .CoefOutS_16(CoefOutS_16),  // sfix19_En23
                                   .CoefOutS_17(CoefOutS_17),  // sfix19_En23
                                   .CoefOutS_18(CoefOutS_18),  // sfix19_En23
                                   .CoefOutS_19(CoefOutS_19),  // sfix19_En23
                                   .CoefOutS_20(CoefOutS_20),  // sfix19_En23
                                   .CoefOutS_21(CoefOutS_21),  // sfix19_En23
                                   .CoefOutS_22(CoefOutS_22),  // sfix19_En23
                                   .CoefOutS_23(CoefOutS_23),  // sfix19_En23
                                   .CoefOutS_24(CoefOutS_24),  // sfix19_En23
                                   .CoefOutS_25(CoefOutS_25),  // sfix19_En23
                                   .CoefOutS_26(CoefOutS_26),  // sfix19_En23
                                   .CoefOutS_27(CoefOutS_27),  // sfix19_En23
                                   .CoefOutS_28(CoefOutS_28),  // sfix19_En23
                                   .CoefOutS_29(CoefOutS_29),  // sfix19_En23
                                   .CoefOutS_30(CoefOutS_30),  // sfix19_En23
                                   .CoefOutS_31(CoefOutS_31),  // sfix19_En23
                                   .CoefOutS_32(CoefOutS_32),  // sfix19_En23
                                   .CoefOutS_33(CoefOutS_33),  // sfix19_En23
                                   .CoefOutS_34(CoefOutS_34),  // sfix19_En23
                                   .CoefOutS_35(CoefOutS_35),  // sfix19_En23
                                   .CoefOutS_36(CoefOutS_36),  // sfix19_En23
                                   .CoefOutS_37(CoefOutS_37),  // sfix19_En23
                                   .CoefOutS_38(CoefOutS_38),  // sfix19_En23
                                   .CoefOutS_39(CoefOutS_39),  // sfix19_En23
                                   .CoefOutS_40(CoefOutS_40),  // sfix19_En23
                                   .CoefOutS_41(CoefOutS_41),  // sfix19_En23
                                   .CoefOutS_42(CoefOutS_42),  // sfix19_En23
                                   .CoefOutS_43(CoefOutS_43),  // sfix19_En23
                                   .CoefOutS_44(CoefOutS_44),  // sfix19_En23
                                   .CoefOutS_45(CoefOutS_45),  // sfix19_En23
                                   .CoefOutS_46(CoefOutS_46),  // sfix19_En23
                                   .CoefOutS_47(CoefOutS_47),  // sfix19_En23
                                   .CoefOutS_48(CoefOutS_48),  // sfix19_En23
                                   .CoefOutS_49(CoefOutS_49),  // sfix19_En23
                                   .CoefOutS_50(CoefOutS_50),  // sfix19_En23
                                   .CoefOutS_51(CoefOutS_51),  // sfix19_En23
                                   .CoefOutS_52(CoefOutS_52),  // sfix19_En23
                                   .CoefOutS_53(CoefOutS_53),  // sfix19_En23
                                   .CoefOutS_54(CoefOutS_54),  // sfix19_En23
                                   .CoefOutS_55(CoefOutS_55),  // sfix19_En23
                                   .CoefOutS_56(CoefOutS_56),  // sfix19_En23
                                   .CoefOutS_57(CoefOutS_57),  // sfix19_En23
                                   .CoefOutS_58(CoefOutS_58),  // sfix19_En23
                                   .CoefOutS_59(CoefOutS_59),  // sfix19_En23
                                   .CoefOutS_60(CoefOutS_60),  // sfix19_En23
                                   .CoefOutS_61(CoefOutS_61),  // sfix19_En23
                                   .CoefOutS_62(CoefOutS_62),  // sfix19_En23
                                   .CoefOutS_63(CoefOutS_63)  // sfix19_En23
                                   );

  subFilter u_subFilter_1_reS (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .dinReg2_0_re(dinReg2_0_im),  // sfix17_En14
                               .coefIn_0(CoefOutS_0),  // sfix19_En23
                               .coefIn_1(CoefOutS_1),  // sfix19_En23
                               .coefIn_2(CoefOutS_2),  // sfix19_En23
                               .coefIn_3(CoefOutS_3),  // sfix19_En23
                               .coefIn_4(CoefOutS_4),  // sfix19_En23
                               .coefIn_5(CoefOutS_5),  // sfix19_En23
                               .coefIn_6(CoefOutS_6),  // sfix19_En23
                               .coefIn_7(CoefOutS_7),  // sfix19_En23
                               .coefIn_8(CoefOutS_8),  // sfix19_En23
                               .coefIn_9(CoefOutS_9),  // sfix19_En23
                               .coefIn_10(CoefOutS_10),  // sfix19_En23
                               .coefIn_11(CoefOutS_11),  // sfix19_En23
                               .coefIn_12(CoefOutS_12),  // sfix19_En23
                               .coefIn_13(CoefOutS_13),  // sfix19_En23
                               .coefIn_14(CoefOutS_14),  // sfix19_En23
                               .coefIn_15(CoefOutS_15),  // sfix19_En23
                               .coefIn_16(CoefOutS_16),  // sfix19_En23
                               .coefIn_17(CoefOutS_17),  // sfix19_En23
                               .coefIn_18(CoefOutS_18),  // sfix19_En23
                               .coefIn_19(CoefOutS_19),  // sfix19_En23
                               .coefIn_20(CoefOutS_20),  // sfix19_En23
                               .coefIn_21(CoefOutS_21),  // sfix19_En23
                               .coefIn_22(CoefOutS_22),  // sfix19_En23
                               .coefIn_23(CoefOutS_23),  // sfix19_En23
                               .coefIn_24(CoefOutS_24),  // sfix19_En23
                               .coefIn_25(CoefOutS_25),  // sfix19_En23
                               .coefIn_26(CoefOutS_26),  // sfix19_En23
                               .coefIn_27(CoefOutS_27),  // sfix19_En23
                               .coefIn_28(CoefOutS_28),  // sfix19_En23
                               .coefIn_29(CoefOutS_29),  // sfix19_En23
                               .coefIn_30(CoefOutS_30),  // sfix19_En23
                               .coefIn_31(CoefOutS_31),  // sfix19_En23
                               .coefIn_32(CoefOutS_32),  // sfix19_En23
                               .coefIn_33(CoefOutS_33),  // sfix19_En23
                               .coefIn_34(CoefOutS_34),  // sfix19_En23
                               .coefIn_35(CoefOutS_35),  // sfix19_En23
                               .coefIn_36(CoefOutS_36),  // sfix19_En23
                               .coefIn_37(CoefOutS_37),  // sfix19_En23
                               .coefIn_38(CoefOutS_38),  // sfix19_En23
                               .coefIn_39(CoefOutS_39),  // sfix19_En23
                               .coefIn_40(CoefOutS_40),  // sfix19_En23
                               .coefIn_41(CoefOutS_41),  // sfix19_En23
                               .coefIn_42(CoefOutS_42),  // sfix19_En23
                               .coefIn_43(CoefOutS_43),  // sfix19_En23
                               .coefIn_44(CoefOutS_44),  // sfix19_En23
                               .coefIn_45(CoefOutS_45),  // sfix19_En23
                               .coefIn_46(CoefOutS_46),  // sfix19_En23
                               .coefIn_47(CoefOutS_47),  // sfix19_En23
                               .coefIn_48(CoefOutS_48),  // sfix19_En23
                               .coefIn_49(CoefOutS_49),  // sfix19_En23
                               .coefIn_50(CoefOutS_50),  // sfix19_En23
                               .coefIn_51(CoefOutS_51),  // sfix19_En23
                               .coefIn_52(CoefOutS_52),  // sfix19_En23
                               .coefIn_53(CoefOutS_53),  // sfix19_En23
                               .coefIn_54(CoefOutS_54),  // sfix19_En23
                               .coefIn_55(CoefOutS_55),  // sfix19_En23
                               .coefIn_56(CoefOutS_56),  // sfix19_En23
                               .coefIn_57(CoefOutS_57),  // sfix19_En23
                               .coefIn_58(CoefOutS_58),  // sfix19_En23
                               .coefIn_59(CoefOutS_59),  // sfix19_En23
                               .coefIn_60(CoefOutS_60),  // sfix19_En23
                               .coefIn_61(CoefOutS_61),  // sfix19_En23
                               .coefIn_62(CoefOutS_62),  // sfix19_En23
                               .coefIn_63(CoefOutS_63),  // sfix19_En23
                               .dinRegVld(dinReg2Vld),
                               .syncReset(syncReset),
                               .dout_1_re(dout_1_M),  // sfix40_En37
                               .doutVld(doutVld_M)
                               );

  assign adder_add_cast_2 = {dout_1_M[39], dout_1_M};
  assign adder_add_cast_3 = {dout_1_I[39], dout_1_I};
  assign dout_1_i_1 = adder_add_cast_2 + adder_add_cast_3;



  assign dout_1_cast_i = dout_1_i_1[39:0];



  always @(posedge clk)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        dout_1_im <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_im <= 40'sh0000000000;
          end
          else begin
            dout_1_im <= dout_1_cast_i;
          end
        end
      end
    end



  assign dataOut_im = dout_1_im;

  always @(posedge clk)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        doutVldReg <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            doutVldReg <= 1'b0;
          end
          else begin
            doutVldReg <= doutVld;
          end
        end
      end
    end



  assign validOut = doutVldReg;

endmodule  // FilterBank

