// -------------------------------------------------------------
// 
// File Name: hdl_project_verilog\hdlsrc\project_detect\FilterCoef_block1.v
// Created: 2021-02-13 17:18:24
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterCoef_block1
// Source Path: project_detect/Pulse Detector/Discrete FIR Filter HDL Optimized/FilterBank/FilterCoef
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterCoef_block1
          (CoefOutI_0,
           CoefOutI_1,
           CoefOutI_2,
           CoefOutI_3,
           CoefOutI_4,
           CoefOutI_5,
           CoefOutI_6,
           CoefOutI_7,
           CoefOutI_8,
           CoefOutI_9,
           CoefOutI_10,
           CoefOutI_11,
           CoefOutI_12,
           CoefOutI_13,
           CoefOutI_14,
           CoefOutI_15,
           CoefOutI_16,
           CoefOutI_17,
           CoefOutI_18,
           CoefOutI_19,
           CoefOutI_20,
           CoefOutI_21,
           CoefOutI_22,
           CoefOutI_23,
           CoefOutI_24,
           CoefOutI_25,
           CoefOutI_26,
           CoefOutI_27,
           CoefOutI_28,
           CoefOutI_29,
           CoefOutI_30,
           CoefOutI_31,
           CoefOutI_32,
           CoefOutI_33,
           CoefOutI_34,
           CoefOutI_35,
           CoefOutI_36,
           CoefOutI_37,
           CoefOutI_38,
           CoefOutI_39,
           CoefOutI_40,
           CoefOutI_41,
           CoefOutI_42,
           CoefOutI_43,
           CoefOutI_44,
           CoefOutI_45,
           CoefOutI_46,
           CoefOutI_47,
           CoefOutI_48,
           CoefOutI_49,
           CoefOutI_50,
           CoefOutI_51,
           CoefOutI_52,
           CoefOutI_53,
           CoefOutI_54,
           CoefOutI_55,
           CoefOutI_56,
           CoefOutI_57,
           CoefOutI_58,
           CoefOutI_59,
           CoefOutI_60,
           CoefOutI_61,
           CoefOutI_62,
           CoefOutI_63);


  output  signed [18:0] CoefOutI_0;  // sfix19_En23
  output  signed [18:0] CoefOutI_1;  // sfix19_En23
  output  signed [18:0] CoefOutI_2;  // sfix19_En23
  output  signed [18:0] CoefOutI_3;  // sfix19_En23
  output  signed [18:0] CoefOutI_4;  // sfix19_En23
  output  signed [18:0] CoefOutI_5;  // sfix19_En23
  output  signed [18:0] CoefOutI_6;  // sfix19_En23
  output  signed [18:0] CoefOutI_7;  // sfix19_En23
  output  signed [18:0] CoefOutI_8;  // sfix19_En23
  output  signed [18:0] CoefOutI_9;  // sfix19_En23
  output  signed [18:0] CoefOutI_10;  // sfix19_En23
  output  signed [18:0] CoefOutI_11;  // sfix19_En23
  output  signed [18:0] CoefOutI_12;  // sfix19_En23
  output  signed [18:0] CoefOutI_13;  // sfix19_En23
  output  signed [18:0] CoefOutI_14;  // sfix19_En23
  output  signed [18:0] CoefOutI_15;  // sfix19_En23
  output  signed [18:0] CoefOutI_16;  // sfix19_En23
  output  signed [18:0] CoefOutI_17;  // sfix19_En23
  output  signed [18:0] CoefOutI_18;  // sfix19_En23
  output  signed [18:0] CoefOutI_19;  // sfix19_En23
  output  signed [18:0] CoefOutI_20;  // sfix19_En23
  output  signed [18:0] CoefOutI_21;  // sfix19_En23
  output  signed [18:0] CoefOutI_22;  // sfix19_En23
  output  signed [18:0] CoefOutI_23;  // sfix19_En23
  output  signed [18:0] CoefOutI_24;  // sfix19_En23
  output  signed [18:0] CoefOutI_25;  // sfix19_En23
  output  signed [18:0] CoefOutI_26;  // sfix19_En23
  output  signed [18:0] CoefOutI_27;  // sfix19_En23
  output  signed [18:0] CoefOutI_28;  // sfix19_En23
  output  signed [18:0] CoefOutI_29;  // sfix19_En23
  output  signed [18:0] CoefOutI_30;  // sfix19_En23
  output  signed [18:0] CoefOutI_31;  // sfix19_En23
  output  signed [18:0] CoefOutI_32;  // sfix19_En23
  output  signed [18:0] CoefOutI_33;  // sfix19_En23
  output  signed [18:0] CoefOutI_34;  // sfix19_En23
  output  signed [18:0] CoefOutI_35;  // sfix19_En23
  output  signed [18:0] CoefOutI_36;  // sfix19_En23
  output  signed [18:0] CoefOutI_37;  // sfix19_En23
  output  signed [18:0] CoefOutI_38;  // sfix19_En23
  output  signed [18:0] CoefOutI_39;  // sfix19_En23
  output  signed [18:0] CoefOutI_40;  // sfix19_En23
  output  signed [18:0] CoefOutI_41;  // sfix19_En23
  output  signed [18:0] CoefOutI_42;  // sfix19_En23
  output  signed [18:0] CoefOutI_43;  // sfix19_En23
  output  signed [18:0] CoefOutI_44;  // sfix19_En23
  output  signed [18:0] CoefOutI_45;  // sfix19_En23
  output  signed [18:0] CoefOutI_46;  // sfix19_En23
  output  signed [18:0] CoefOutI_47;  // sfix19_En23
  output  signed [18:0] CoefOutI_48;  // sfix19_En23
  output  signed [18:0] CoefOutI_49;  // sfix19_En23
  output  signed [18:0] CoefOutI_50;  // sfix19_En23
  output  signed [18:0] CoefOutI_51;  // sfix19_En23
  output  signed [18:0] CoefOutI_52;  // sfix19_En23
  output  signed [18:0] CoefOutI_53;  // sfix19_En23
  output  signed [18:0] CoefOutI_54;  // sfix19_En23
  output  signed [18:0] CoefOutI_55;  // sfix19_En23
  output  signed [18:0] CoefOutI_56;  // sfix19_En23
  output  signed [18:0] CoefOutI_57;  // sfix19_En23
  output  signed [18:0] CoefOutI_58;  // sfix19_En23
  output  signed [18:0] CoefOutI_59;  // sfix19_En23
  output  signed [18:0] CoefOutI_60;  // sfix19_En23
  output  signed [18:0] CoefOutI_61;  // sfix19_En23
  output  signed [18:0] CoefOutI_62;  // sfix19_En23
  output  signed [18:0] CoefOutI_63;  // sfix19_En23


  wire signed [18:0] CoefData;  // sfix19_En23
  wire signed [18:0] CoefData_1;  // sfix19_En23
  wire signed [18:0] CoefData_2;  // sfix19_En23
  wire signed [18:0] CoefData_3;  // sfix19_En23
  wire signed [18:0] CoefData_4;  // sfix19_En23
  wire signed [18:0] CoefData_5;  // sfix19_En23
  wire signed [18:0] CoefData_6;  // sfix19_En23
  wire signed [18:0] CoefData_7;  // sfix19_En23
  wire signed [18:0] CoefData_8;  // sfix19_En23
  wire signed [18:0] CoefData_9;  // sfix19_En23
  wire signed [18:0] CoefData_10;  // sfix19_En23
  wire signed [18:0] CoefData_11;  // sfix19_En23
  wire signed [18:0] CoefData_12;  // sfix19_En23
  wire signed [18:0] CoefData_13;  // sfix19_En23
  wire signed [18:0] CoefData_14;  // sfix19_En23
  wire signed [18:0] CoefData_15;  // sfix19_En23
  wire signed [18:0] CoefData_16;  // sfix19_En23
  wire signed [18:0] CoefData_17;  // sfix19_En23
  wire signed [18:0] CoefData_18;  // sfix19_En23
  wire signed [18:0] CoefData_19;  // sfix19_En23
  wire signed [18:0] CoefData_20;  // sfix19_En23
  wire signed [18:0] CoefData_21;  // sfix19_En23
  wire signed [18:0] CoefData_22;  // sfix19_En23
  wire signed [18:0] CoefData_23;  // sfix19_En23
  wire signed [18:0] CoefData_24;  // sfix19_En23
  wire signed [18:0] CoefData_25;  // sfix19_En23
  wire signed [18:0] CoefData_26;  // sfix19_En23
  wire signed [18:0] CoefData_27;  // sfix19_En23
  wire signed [18:0] CoefData_28;  // sfix19_En23
  wire signed [18:0] CoefData_29;  // sfix19_En23
  wire signed [18:0] CoefData_30;  // sfix19_En23
  wire signed [18:0] CoefData_31;  // sfix19_En23
  wire signed [18:0] CoefData_32;  // sfix19_En23
  wire signed [18:0] CoefData_33;  // sfix19_En23
  wire signed [18:0] CoefData_34;  // sfix19_En23
  wire signed [18:0] CoefData_35;  // sfix19_En23
  wire signed [18:0] CoefData_36;  // sfix19_En23
  wire signed [18:0] CoefData_37;  // sfix19_En23
  wire signed [18:0] CoefData_38;  // sfix19_En23
  wire signed [18:0] CoefData_39;  // sfix19_En23
  wire signed [18:0] CoefData_40;  // sfix19_En23
  wire signed [18:0] CoefData_41;  // sfix19_En23
  wire signed [18:0] CoefData_42;  // sfix19_En23
  wire signed [18:0] CoefData_43;  // sfix19_En23
  wire signed [18:0] CoefData_44;  // sfix19_En23
  wire signed [18:0] CoefData_45;  // sfix19_En23
  wire signed [18:0] CoefData_46;  // sfix19_En23
  wire signed [18:0] CoefData_47;  // sfix19_En23
  wire signed [18:0] CoefData_48;  // sfix19_En23
  wire signed [18:0] CoefData_49;  // sfix19_En23
  wire signed [18:0] CoefData_50;  // sfix19_En23
  wire signed [18:0] CoefData_51;  // sfix19_En23
  wire signed [18:0] CoefData_52;  // sfix19_En23
  wire signed [18:0] CoefData_53;  // sfix19_En23
  wire signed [18:0] CoefData_54;  // sfix19_En23
  wire signed [18:0] CoefData_55;  // sfix19_En23
  wire signed [18:0] CoefData_56;  // sfix19_En23
  wire signed [18:0] CoefData_57;  // sfix19_En23
  wire signed [18:0] CoefData_58;  // sfix19_En23
  wire signed [18:0] CoefData_59;  // sfix19_En23
  wire signed [18:0] CoefData_60;  // sfix19_En23
  wire signed [18:0] CoefData_61;  // sfix19_En23
  wire signed [18:0] CoefData_62;  // sfix19_En23
  wire signed [18:0] CoefData_63;  // sfix19_En23


  // CoefReg_1
  assign CoefData = 19'sb0011110011000000100;



  assign CoefOutI_0 = CoefData;

  // CoefReg_2
  assign CoefData_1 = 19'sb0000001001100101001;



  assign CoefOutI_1 = CoefData_1;

  // CoefReg_3
  assign CoefData_2 = 19'sb1100000000001000011;



  assign CoefOutI_2 = CoefData_2;

  // CoefReg_4
  assign CoefData_3 = 19'sb0011111111111111100;



  assign CoefOutI_3 = CoefData_3;

  // CoefReg_5
  assign CoefData_4 = 19'sb1100000011011101010;



  assign CoefOutI_4 = CoefData_4;

  // CoefReg_6
  assign CoefData_5 = 19'sb0010000010101011111;



  assign CoefOutI_5 = CoefData_5;

  // CoefReg_7
  assign CoefData_6 = 19'sb1100101000001011111;



  assign CoefOutI_6 = CoefData_6;

  // CoefReg_8
  assign CoefData_7 = 19'sb0001000000000100000;



  assign CoefOutI_7 = CoefData_7;

  // CoefReg_9
  assign CoefData_8 = 19'sb1111111101010111101;



  assign CoefOutI_8 = CoefData_8;

  // CoefReg_10
  assign CoefData_9 = 19'sb1101010001111011111;



  assign CoefOutI_9 = CoefData_9;

  // CoefReg_11
  assign CoefData_10 = 19'sb1100100101101000011;



  assign CoefOutI_10 = CoefData_10;

  // CoefReg_12
  assign CoefData_11 = 19'sb0011010011110100100;



  assign CoefOutI_11 = CoefData_11;

  // CoefReg_13
  assign CoefData_12 = 19'sb0011100111011011101;



  assign CoefOutI_12 = CoefData_12;

  // CoefReg_14
  assign CoefData_13 = 19'sb1100000011011010100;



  assign CoefOutI_13 = CoefData_13;

  // CoefReg_15
  assign CoefData_14 = 19'sb0011111111111000111;



  assign CoefOutI_14 = CoefData_14;

  // CoefReg_16
  assign CoefData_15 = 19'sb0011110111101100111;



  assign CoefOutI_15 = CoefData_15;

  // CoefReg_17
  assign CoefData_16 = 19'sb0011001011100100010;



  assign CoefOutI_16 = CoefData_16;

  // CoefReg_18
  assign CoefData_17 = 19'sb1110101010001010111;



  assign CoefOutI_17 = CoefData_17;

  // CoefReg_19
  assign CoefData_18 = 19'sb1111101111100011000;



  assign CoefOutI_18 = CoefData_18;

  // CoefReg_20
  assign CoefData_19 = 19'sb1100010011111000000;



  assign CoefOutI_19 = CoefData_19;

  // CoefReg_21
  assign CoefData_20 = 19'sb0011110101101111110;



  assign CoefOutI_20 = CoefData_20;

  // CoefReg_22
  assign CoefData_21 = 19'sb0011111110110010010;



  assign CoefOutI_21 = CoefData_21;

  // CoefReg_23
  assign CoefData_22 = 19'sb1101010010100101111;



  assign CoefOutI_22 = CoefData_22;

  // CoefReg_24
  assign CoefData_23 = 19'sb1110011111111000101;



  assign CoefOutI_23 = CoefData_23;

  // CoefReg_25
  assign CoefData_24 = 19'sb1111001001000001101;



  assign CoefOutI_24 = CoefData_24;

  // CoefReg_26
  assign CoefData_25 = 19'sb0001001110110001010;



  assign CoefOutI_25 = CoefData_25;

  // CoefReg_27
  assign CoefData_26 = 19'sb1100010110011010101;



  assign CoefOutI_26 = CoefData_26;

  // CoefReg_28
  assign CoefData_27 = 19'sb0011110000110001011;



  assign CoefOutI_27 = CoefData_27;

  // CoefReg_29
  assign CoefData_28 = 19'sb0011100101001101101;



  assign CoefOutI_28 = CoefData_28;

  // CoefReg_30
  assign CoefData_29 = 19'sb1101101101010010001;



  assign CoefOutI_29 = CoefData_29;

  // CoefReg_31
  assign CoefData_30 = 19'sb1110110110110001011;



  assign CoefOutI_30 = CoefData_30;

  // CoefReg_32
  assign CoefData_31 = 19'sb1100000011101001111;



  assign CoefOutI_31 = CoefData_31;

  // CoefReg_33
  assign CoefData_32 = 19'sb1111001101001000111;



  assign CoefOutI_32 = CoefData_32;

  // CoefReg_34
  assign CoefData_33 = 19'sb0011110110010011001;



  assign CoefOutI_33 = CoefData_33;

  // CoefReg_35
  assign CoefData_34 = 19'sb1100011110110000001;



  assign CoefOutI_34 = CoefData_34;

  // CoefReg_36
  assign CoefData_35 = 19'sb0011010100001010100;



  assign CoefOutI_35 = CoefData_35;

  // CoefReg_37
  assign CoefData_36 = 19'sb1101011111100110001;



  assign CoefOutI_36 = CoefData_36;

  // CoefReg_38
  assign CoefData_37 = 19'sb0011111111110000110;



  assign CoefOutI_37 = CoefData_37;

  // CoefReg_39
  assign CoefData_38 = 19'sb0011111111101100101;



  assign CoefOutI_38 = CoefData_38;

  // CoefReg_40
  assign CoefData_39 = 19'sb0011100110110000110;



  assign CoefOutI_39 = CoefData_39;

  // CoefReg_41
  assign CoefData_40 = 19'sb0001100111001001111;



  assign CoefOutI_40 = CoefData_40;

  // CoefReg_42
  assign CoefData_41 = 19'sb0011001111111011011;



  assign CoefOutI_41 = CoefData_41;

  // CoefReg_43
  assign CoefData_42 = 19'sb1111000111000010100;



  assign CoefOutI_42 = CoefData_42;

  // CoefReg_44
  assign CoefData_43 = 19'sb0011010100011001101;



  assign CoefOutI_43 = CoefData_43;

  // CoefReg_45
  assign CoefData_44 = 19'sb0001000000011101001;



  assign CoefOutI_44 = CoefData_44;

  // CoefReg_46
  assign CoefData_45 = 19'sb0011110111000011010;



  assign CoefOutI_45 = CoefData_45;

  // CoefReg_47
  assign CoefData_46 = 19'sb0010000001010010111;



  assign CoefOutI_46 = CoefData_46;

  // CoefReg_48
  assign CoefData_47 = 19'sb1110000111001010011;



  assign CoefOutI_47 = CoefData_47;

  // CoefReg_49
  assign CoefData_48 = 19'sb1100111000110101000;



  assign CoefOutI_48 = CoefData_48;

  // CoefReg_50
  assign CoefData_49 = 19'sb0011110011010101001;



  assign CoefOutI_49 = CoefData_49;

  // CoefReg_51
  assign CoefData_50 = 19'sb1111101000100000101;



  assign CoefOutI_50 = CoefData_50;

  // CoefReg_52
  assign CoefData_51 = 19'sb0001000100000100011;



  assign CoefOutI_51 = CoefData_51;

  // CoefReg_53
  assign CoefData_52 = 19'sb0000101111000010001;



  assign CoefOutI_52 = CoefData_52;

  // CoefReg_54
  assign CoefData_53 = 19'sb1100101001111011110;



  assign CoefOutI_53 = CoefData_53;

  // CoefReg_55
  assign CoefData_54 = 19'sb0000111000000001010;



  assign CoefOutI_54 = CoefData_54;

  // CoefReg_56
  assign CoefData_55 = 19'sb0001000011100010101;



  assign CoefOutI_55 = CoefData_55;

  // CoefReg_57
  assign CoefData_56 = 19'sb0001001010010100101;



  assign CoefOutI_56 = CoefData_56;

  // CoefReg_58
  assign CoefData_57 = 19'sb1100000100000110000;



  assign CoefOutI_57 = CoefData_57;

  // CoefReg_59
  assign CoefData_58 = 19'sb1101101100101111110;



  assign CoefOutI_58 = CoefData_58;

  // CoefReg_60
  assign CoefData_59 = 19'sb0010111101001100011;



  assign CoefOutI_59 = CoefData_59;

  // CoefReg_61
  assign CoefData_60 = 19'sb0010000100100011101;



  assign CoefOutI_60 = CoefData_60;

  // CoefReg_62
  assign CoefData_61 = 19'sb1101001000101111000;



  assign CoefOutI_61 = CoefData_61;

  // CoefReg_63
  assign CoefData_62 = 19'sb0010001110110101101;



  assign CoefOutI_62 = CoefData_62;

  // CoefReg_64
  assign CoefData_63 = 19'sb0011101011000111110;



  assign CoefOutI_63 = CoefData_63;

endmodule  // FilterCoef_block1

