// -------------------------------------------------------------
// 
// File Name: hdl_project_verilog\hdlsrc\project_detect\FilterCoef.v
// Created: 2021-02-13 17:18:24
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterCoef
// Source Path: project_detect/Pulse Detector/Discrete FIR Filter HDL Optimized/FilterBank/FilterCoef
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterCoef
          (CoefOutP_0,
           CoefOutP_1,
           CoefOutP_2,
           CoefOutP_3,
           CoefOutP_4,
           CoefOutP_5,
           CoefOutP_6,
           CoefOutP_7,
           CoefOutP_8,
           CoefOutP_9,
           CoefOutP_10,
           CoefOutP_11,
           CoefOutP_12,
           CoefOutP_13,
           CoefOutP_14,
           CoefOutP_15,
           CoefOutP_16,
           CoefOutP_17,
           CoefOutP_18,
           CoefOutP_19,
           CoefOutP_20,
           CoefOutP_21,
           CoefOutP_22,
           CoefOutP_23,
           CoefOutP_24,
           CoefOutP_25,
           CoefOutP_26,
           CoefOutP_27,
           CoefOutP_28,
           CoefOutP_29,
           CoefOutP_30,
           CoefOutP_31,
           CoefOutP_32,
           CoefOutP_33,
           CoefOutP_34,
           CoefOutP_35,
           CoefOutP_36,
           CoefOutP_37,
           CoefOutP_38,
           CoefOutP_39,
           CoefOutP_40,
           CoefOutP_41,
           CoefOutP_42,
           CoefOutP_43,
           CoefOutP_44,
           CoefOutP_45,
           CoefOutP_46,
           CoefOutP_47,
           CoefOutP_48,
           CoefOutP_49,
           CoefOutP_50,
           CoefOutP_51,
           CoefOutP_52,
           CoefOutP_53,
           CoefOutP_54,
           CoefOutP_55,
           CoefOutP_56,
           CoefOutP_57,
           CoefOutP_58,
           CoefOutP_59,
           CoefOutP_60,
           CoefOutP_61,
           CoefOutP_62,
           CoefOutP_63);


  output  signed [18:0] CoefOutP_0;  // sfix19_En23
  output  signed [18:0] CoefOutP_1;  // sfix19_En23
  output  signed [18:0] CoefOutP_2;  // sfix19_En23
  output  signed [18:0] CoefOutP_3;  // sfix19_En23
  output  signed [18:0] CoefOutP_4;  // sfix19_En23
  output  signed [18:0] CoefOutP_5;  // sfix19_En23
  output  signed [18:0] CoefOutP_6;  // sfix19_En23
  output  signed [18:0] CoefOutP_7;  // sfix19_En23
  output  signed [18:0] CoefOutP_8;  // sfix19_En23
  output  signed [18:0] CoefOutP_9;  // sfix19_En23
  output  signed [18:0] CoefOutP_10;  // sfix19_En23
  output  signed [18:0] CoefOutP_11;  // sfix19_En23
  output  signed [18:0] CoefOutP_12;  // sfix19_En23
  output  signed [18:0] CoefOutP_13;  // sfix19_En23
  output  signed [18:0] CoefOutP_14;  // sfix19_En23
  output  signed [18:0] CoefOutP_15;  // sfix19_En23
  output  signed [18:0] CoefOutP_16;  // sfix19_En23
  output  signed [18:0] CoefOutP_17;  // sfix19_En23
  output  signed [18:0] CoefOutP_18;  // sfix19_En23
  output  signed [18:0] CoefOutP_19;  // sfix19_En23
  output  signed [18:0] CoefOutP_20;  // sfix19_En23
  output  signed [18:0] CoefOutP_21;  // sfix19_En23
  output  signed [18:0] CoefOutP_22;  // sfix19_En23
  output  signed [18:0] CoefOutP_23;  // sfix19_En23
  output  signed [18:0] CoefOutP_24;  // sfix19_En23
  output  signed [18:0] CoefOutP_25;  // sfix19_En23
  output  signed [18:0] CoefOutP_26;  // sfix19_En23
  output  signed [18:0] CoefOutP_27;  // sfix19_En23
  output  signed [18:0] CoefOutP_28;  // sfix19_En23
  output  signed [18:0] CoefOutP_29;  // sfix19_En23
  output  signed [18:0] CoefOutP_30;  // sfix19_En23
  output  signed [18:0] CoefOutP_31;  // sfix19_En23
  output  signed [18:0] CoefOutP_32;  // sfix19_En23
  output  signed [18:0] CoefOutP_33;  // sfix19_En23
  output  signed [18:0] CoefOutP_34;  // sfix19_En23
  output  signed [18:0] CoefOutP_35;  // sfix19_En23
  output  signed [18:0] CoefOutP_36;  // sfix19_En23
  output  signed [18:0] CoefOutP_37;  // sfix19_En23
  output  signed [18:0] CoefOutP_38;  // sfix19_En23
  output  signed [18:0] CoefOutP_39;  // sfix19_En23
  output  signed [18:0] CoefOutP_40;  // sfix19_En23
  output  signed [18:0] CoefOutP_41;  // sfix19_En23
  output  signed [18:0] CoefOutP_42;  // sfix19_En23
  output  signed [18:0] CoefOutP_43;  // sfix19_En23
  output  signed [18:0] CoefOutP_44;  // sfix19_En23
  output  signed [18:0] CoefOutP_45;  // sfix19_En23
  output  signed [18:0] CoefOutP_46;  // sfix19_En23
  output  signed [18:0] CoefOutP_47;  // sfix19_En23
  output  signed [18:0] CoefOutP_48;  // sfix19_En23
  output  signed [18:0] CoefOutP_49;  // sfix19_En23
  output  signed [18:0] CoefOutP_50;  // sfix19_En23
  output  signed [18:0] CoefOutP_51;  // sfix19_En23
  output  signed [18:0] CoefOutP_52;  // sfix19_En23
  output  signed [18:0] CoefOutP_53;  // sfix19_En23
  output  signed [18:0] CoefOutP_54;  // sfix19_En23
  output  signed [18:0] CoefOutP_55;  // sfix19_En23
  output  signed [18:0] CoefOutP_56;  // sfix19_En23
  output  signed [18:0] CoefOutP_57;  // sfix19_En23
  output  signed [18:0] CoefOutP_58;  // sfix19_En23
  output  signed [18:0] CoefOutP_59;  // sfix19_En23
  output  signed [18:0] CoefOutP_60;  // sfix19_En23
  output  signed [18:0] CoefOutP_61;  // sfix19_En23
  output  signed [18:0] CoefOutP_62;  // sfix19_En23
  output  signed [18:0] CoefOutP_63;  // sfix19_En23


  wire signed [18:0] CoefData;  // sfix19_En23
  wire signed [18:0] CoefData_1;  // sfix19_En23
  wire signed [18:0] CoefData_2;  // sfix19_En23
  wire signed [18:0] CoefData_3;  // sfix19_En23
  wire signed [18:0] CoefData_4;  // sfix19_En23
  wire signed [18:0] CoefData_5;  // sfix19_En23
  wire signed [18:0] CoefData_6;  // sfix19_En23
  wire signed [18:0] CoefData_7;  // sfix19_En23
  wire signed [18:0] CoefData_8;  // sfix19_En23
  wire signed [18:0] CoefData_9;  // sfix19_En23
  wire signed [18:0] CoefData_10;  // sfix19_En23
  wire signed [18:0] CoefData_11;  // sfix19_En23
  wire signed [18:0] CoefData_12;  // sfix19_En23
  wire signed [18:0] CoefData_13;  // sfix19_En23
  wire signed [18:0] CoefData_14;  // sfix19_En23
  wire signed [18:0] CoefData_15;  // sfix19_En23
  wire signed [18:0] CoefData_16;  // sfix19_En23
  wire signed [18:0] CoefData_17;  // sfix19_En23
  wire signed [18:0] CoefData_18;  // sfix19_En23
  wire signed [18:0] CoefData_19;  // sfix19_En23
  wire signed [18:0] CoefData_20;  // sfix19_En23
  wire signed [18:0] CoefData_21;  // sfix19_En23
  wire signed [18:0] CoefData_22;  // sfix19_En23
  wire signed [18:0] CoefData_23;  // sfix19_En23
  wire signed [18:0] CoefData_24;  // sfix19_En23
  wire signed [18:0] CoefData_25;  // sfix19_En23
  wire signed [18:0] CoefData_26;  // sfix19_En23
  wire signed [18:0] CoefData_27;  // sfix19_En23
  wire signed [18:0] CoefData_28;  // sfix19_En23
  wire signed [18:0] CoefData_29;  // sfix19_En23
  wire signed [18:0] CoefData_30;  // sfix19_En23
  wire signed [18:0] CoefData_31;  // sfix19_En23
  wire signed [18:0] CoefData_32;  // sfix19_En23
  wire signed [18:0] CoefData_33;  // sfix19_En23
  wire signed [18:0] CoefData_34;  // sfix19_En23
  wire signed [18:0] CoefData_35;  // sfix19_En23
  wire signed [18:0] CoefData_36;  // sfix19_En23
  wire signed [18:0] CoefData_37;  // sfix19_En23
  wire signed [18:0] CoefData_38;  // sfix19_En23
  wire signed [18:0] CoefData_39;  // sfix19_En23
  wire signed [18:0] CoefData_40;  // sfix19_En23
  wire signed [18:0] CoefData_41;  // sfix19_En23
  wire signed [18:0] CoefData_42;  // sfix19_En23
  wire signed [18:0] CoefData_43;  // sfix19_En23
  wire signed [18:0] CoefData_44;  // sfix19_En23
  wire signed [18:0] CoefData_45;  // sfix19_En23
  wire signed [18:0] CoefData_46;  // sfix19_En23
  wire signed [18:0] CoefData_47;  // sfix19_En23
  wire signed [18:0] CoefData_48;  // sfix19_En23
  wire signed [18:0] CoefData_49;  // sfix19_En23
  wire signed [18:0] CoefData_50;  // sfix19_En23
  wire signed [18:0] CoefData_51;  // sfix19_En23
  wire signed [18:0] CoefData_52;  // sfix19_En23
  wire signed [18:0] CoefData_53;  // sfix19_En23
  wire signed [18:0] CoefData_54;  // sfix19_En23
  wire signed [18:0] CoefData_55;  // sfix19_En23
  wire signed [18:0] CoefData_56;  // sfix19_En23
  wire signed [18:0] CoefData_57;  // sfix19_En23
  wire signed [18:0] CoefData_58;  // sfix19_En23
  wire signed [18:0] CoefData_59;  // sfix19_En23
  wire signed [18:0] CoefData_60;  // sfix19_En23
  wire signed [18:0] CoefData_61;  // sfix19_En23
  wire signed [18:0] CoefData_62;  // sfix19_En23
  wire signed [18:0] CoefData_63;  // sfix19_En23


  // CoefReg_1
  assign CoefData = 19'sb0010100010011111010;



  assign CoefOutP_0 = CoefData;

  // CoefReg_2
  assign CoefData_1 = 19'sb1100001001110000101;



  assign CoefOutP_1 = CoefData_1;

  // CoefReg_3
  assign CoefData_2 = 19'sb1011110111111100000;



  assign CoefOutP_2 = CoefData_2;

  // CoefReg_4
  assign CoefData_3 = 19'sb0100000010000001111;



  assign CoefOutP_3 = CoefData_3;

  // CoefReg_5
  assign CoefData_4 = 19'sb1100101101011001000;



  assign CoefOutP_4 = CoefData_4;

  // CoefReg_6
  assign CoefData_5 = 19'sb1110100110100011100;



  assign CoefOutP_5 = CoefData_5;

  // CoefReg_7
  assign CoefData_6 = 19'sb1010011110011111011;



  assign CoefOutP_6 = CoefData_6;

  // CoefReg_8
  assign CoefData_7 = 19'sb0100110111111010110;



  assign CoefOutP_7 = CoefData_7;

  // CoefReg_9
  assign CoefData_8 = 19'sb1011111101011000100;



  assign CoefOutP_8 = CoefData_8;

  // CoefReg_10
  assign CoefData_9 = 19'sb0000001101101001110;



  assign CoefOutP_9 = CoefData_9;

  // CoefReg_11
  assign CoefData_10 = 19'sb1110101011001111001;



  assign CoefOutP_10 = CoefData_10;

  // CoefReg_12
  assign CoefData_11 = 19'sb0001000100000011101;



  assign CoefOutP_11 = CoefData_11;

  // CoefReg_13
  assign CoefData_12 = 19'sb0001111010000000000;



  assign CoefOutP_12 = CoefData_12;

  // CoefReg_14
  assign CoefData_13 = 19'sb1011011001101111010;



  assign CoefOutP_13 = CoefData_13;

  // CoefReg_15
  assign CoefData_14 = 19'sb0100000111011011010;



  assign CoefOutP_14 = CoefData_14;

  // CoefReg_16
  assign CoefData_15 = 19'sb0010110111000011000;



  assign CoefOutP_15 = CoefData_15;

  // CoefReg_17
  assign CoefData_16 = 19'sb0000110000010101100;



  assign CoefOutP_16 = CoefData_16;

  // CoefReg_18
  assign CoefData_17 = 19'sb1010111000111111001;



  assign CoefOutP_17 = CoefData_17;

  // CoefReg_19
  assign CoefData_18 = 19'sb1011110000000100111;



  assign CoefOutP_18 = CoefData_18;

  // CoefReg_20
  assign CoefData_19 = 19'sb1101110110110001100;



  assign CoefOutP_19 = CoefData_19;

  // CoefReg_21
  assign CoefData_20 = 19'sb0100111101011110100;



  assign CoefOutP_20 = CoefData_20;

  // CoefReg_22
  assign CoefData_21 = 19'sb0100010111101101001;



  assign CoefOutP_21 = CoefData_21;

  // CoefReg_23
  assign CoefData_22 = 19'sb1010010110010001010;



  assign CoefOutP_22 = CoefData_22;

  // CoefReg_24
  assign CoefData_23 = 19'sb1010110010100111010;



  assign CoefOutP_23 = CoefData_23;

  // CoefReg_25
  assign CoefData_24 = 19'sb0011000011000011011;



  assign CoefOutP_24 = CoefData_24;

  // CoefReg_26
  assign CoefData_25 = 19'sb0101000010010110011;



  assign CoefOutP_25 = CoefData_25;

  // CoefReg_27
  assign CoefData_26 = 19'sb1010101101101010000;



  assign CoefOutP_26 = CoefData_26;

  // CoefReg_28
  assign CoefData_27 = 19'sb0010011001110010111;



  assign CoefOutP_27 = CoefData_27;

  // CoefReg_29
  assign CoefData_28 = 19'sb0101010111001110000;



  assign CoefOutP_28 = CoefData_28;

  // CoefReg_30
  assign CoefData_29 = 19'sb0000111111000100100;



  assign CoefOutP_29 = CoefData_29;

  // CoefReg_31
  assign CoefData_30 = 19'sb0010101100000100110;



  assign CoefOutP_30 = CoefData_30;

  // CoefReg_32
  assign CoefData_31 = 19'sb1011011000100011100;



  assign CoefOutP_31 = CoefData_31;

  // CoefReg_33
  assign CoefData_32 = 19'sb0011001000000010010;



  assign CoefOutP_32 = CoefData_32;

  // CoefReg_34
  assign CoefData_33 = 19'sb0010110000011111101;



  assign CoefOutP_33 = CoefData_33;

  // CoefReg_35
  assign CoefData_34 = 19'sb1110011000011001111;



  assign CoefOutP_34 = CoefData_34;

  // CoefReg_36
  assign CoefData_35 = 19'sb0001000100111010000;



  assign CoefOutP_35 = CoefData_35;

  // CoefReg_37
  assign CoefData_36 = 19'sb1010011000000101001;



  assign CoefOutP_36 = CoefData_36;

  // CoefReg_38
  assign CoefData_37 = 19'sb0011110100101110000;



  assign CoefOutP_37 = CoefData_37;

  // CoefReg_39
  assign CoefData_38 = 19'sb0100001100001001001;



  assign CoefOutP_38 = CoefData_38;

  // CoefReg_40
  assign CoefData_39 = 19'sb0001110111111011010;



  assign CoefOutP_39 = CoefData_39;

  // CoefReg_41
  assign CoefData_40 = 19'sb0101010001011100111;



  assign CoefOutP_40 = CoefData_40;

  // CoefReg_42
  assign CoefData_41 = 19'sb0101100101010001000;



  assign CoefOutP_41 = CoefData_41;

  // CoefReg_43
  assign CoefData_42 = 19'sb0011000000100111110;



  assign CoefOutP_42 = CoefData_42;

  // CoefReg_44
  assign CoefData_43 = 19'sb0001000101011111101;



  assign CoefOutP_43 = CoefData_43;

  // CoefReg_45
  assign CoefData_44 = 19'sb0100111000001101011;



  assign CoefOutP_44 = CoefData_44;

  // CoefReg_46
  assign CoefData_45 = 19'sb0100111010001001100;



  assign CoefOutP_45 = CoefData_45;

  // CoefReg_47
  assign CoefData_46 = 19'sb0101011110001111101;



  assign CoefOutP_46 = CoefData_46;

  // CoefReg_48
  assign CoefData_47 = 19'sb1010100101011110100;



  assign CoefOutP_47 = CoefData_47;

  // CoefReg_49
  assign CoefData_48 = 19'sb1111011001101010010;



  assign CoefOutP_48 = CoefData_48;

  // CoefReg_50
  assign CoefData_49 = 19'sb0101000010110111100;



  assign CoefOutP_49 = CoefData_49;

  // CoefReg_51
  assign CoefData_50 = 19'sb1011101001100101110;



  assign CoefOutP_50 = CoefData_50;

  // CoefReg_52
  assign CoefData_51 = 19'sb0100111010110110101;



  assign CoefOutP_51 = CoefData_51;

  // CoefReg_53
  assign CoefData_52 = 19'sb0100101010101011010;



  assign CoefOutP_52 = CoefData_52;

  // CoefReg_54
  assign CoefData_53 = 19'sb1110110110010101010;



  assign CoefOutP_53 = CoefData_53;

  // CoefReg_55
  assign CoefData_54 = 19'sb0100110001110100001;



  assign CoefOutP_54 = CoefData_54;

  // CoefReg_56
  assign CoefData_55 = 19'sb0100111010011110001;



  assign CoefOutP_55 = CoefData_55;

  // CoefReg_57
  assign CoefData_56 = 19'sb1101010101010110010;



  assign CoefOutP_56 = CoefData_56;

  // CoefReg_58
  assign CoefData_57 = 19'sb1011010110100000000;



  assign CoefOutP_57 = CoefData_57;

  // CoefReg_59
  assign CoefData_58 = 19'sb0000111110001001111;



  assign CoefOutP_58 = CoefData_58;

  // CoefReg_60
  assign CoefData_59 = 19'sb0000010000101111000;



  assign CoefOutP_59 = CoefData_59;

  // CoefReg_61
  assign CoefData_60 = 19'sb0101011111100100001;



  assign CoefOutP_60 = CoefData_60;

  // CoefReg_62
  assign CoefData_61 = 19'sb1111111011011110110;



  assign CoefOutP_61 = CoefData_61;

  // CoefReg_63
  assign CoefData_62 = 19'sb0101100011010010001;



  assign CoefOutP_62 = CoefData_62;

  // CoefReg_64
  assign CoefData_63 = 19'sb0101010000011000100;



  assign CoefOutP_63 = CoefData_63;

endmodule  // FilterCoef

