// -------------------------------------------------------------
// 
// File Name: hdl_project_verilog\hdlsrc\project_detect\subFilter.v
// Created: 2021-02-13 17:18:24
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter
// Source Path: project_detect/Pulse Detector/Discrete FIR Filter HDL Optimized/FilterBank/subFilter
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subFilter
          (clk,
           reset,
           enb,
           dinReg2_0_re,
           coefIn_0,
           coefIn_1,
           coefIn_2,
           coefIn_3,
           coefIn_4,
           coefIn_5,
           coefIn_6,
           coefIn_7,
           coefIn_8,
           coefIn_9,
           coefIn_10,
           coefIn_11,
           coefIn_12,
           coefIn_13,
           coefIn_14,
           coefIn_15,
           coefIn_16,
           coefIn_17,
           coefIn_18,
           coefIn_19,
           coefIn_20,
           coefIn_21,
           coefIn_22,
           coefIn_23,
           coefIn_24,
           coefIn_25,
           coefIn_26,
           coefIn_27,
           coefIn_28,
           coefIn_29,
           coefIn_30,
           coefIn_31,
           coefIn_32,
           coefIn_33,
           coefIn_34,
           coefIn_35,
           coefIn_36,
           coefIn_37,
           coefIn_38,
           coefIn_39,
           coefIn_40,
           coefIn_41,
           coefIn_42,
           coefIn_43,
           coefIn_44,
           coefIn_45,
           coefIn_46,
           coefIn_47,
           coefIn_48,
           coefIn_49,
           coefIn_50,
           coefIn_51,
           coefIn_52,
           coefIn_53,
           coefIn_54,
           coefIn_55,
           coefIn_56,
           coefIn_57,
           coefIn_58,
           coefIn_59,
           coefIn_60,
           coefIn_61,
           coefIn_62,
           coefIn_63,
           dinRegVld,
           syncReset,
           dout_1_re,
           doutVld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [16:0] dinReg2_0_re;  // sfix17_En14
  input   signed [18:0] coefIn_0;  // sfix19_En23
  input   signed [18:0] coefIn_1;  // sfix19_En23
  input   signed [18:0] coefIn_2;  // sfix19_En23
  input   signed [18:0] coefIn_3;  // sfix19_En23
  input   signed [18:0] coefIn_4;  // sfix19_En23
  input   signed [18:0] coefIn_5;  // sfix19_En23
  input   signed [18:0] coefIn_6;  // sfix19_En23
  input   signed [18:0] coefIn_7;  // sfix19_En23
  input   signed [18:0] coefIn_8;  // sfix19_En23
  input   signed [18:0] coefIn_9;  // sfix19_En23
  input   signed [18:0] coefIn_10;  // sfix19_En23
  input   signed [18:0] coefIn_11;  // sfix19_En23
  input   signed [18:0] coefIn_12;  // sfix19_En23
  input   signed [18:0] coefIn_13;  // sfix19_En23
  input   signed [18:0] coefIn_14;  // sfix19_En23
  input   signed [18:0] coefIn_15;  // sfix19_En23
  input   signed [18:0] coefIn_16;  // sfix19_En23
  input   signed [18:0] coefIn_17;  // sfix19_En23
  input   signed [18:0] coefIn_18;  // sfix19_En23
  input   signed [18:0] coefIn_19;  // sfix19_En23
  input   signed [18:0] coefIn_20;  // sfix19_En23
  input   signed [18:0] coefIn_21;  // sfix19_En23
  input   signed [18:0] coefIn_22;  // sfix19_En23
  input   signed [18:0] coefIn_23;  // sfix19_En23
  input   signed [18:0] coefIn_24;  // sfix19_En23
  input   signed [18:0] coefIn_25;  // sfix19_En23
  input   signed [18:0] coefIn_26;  // sfix19_En23
  input   signed [18:0] coefIn_27;  // sfix19_En23
  input   signed [18:0] coefIn_28;  // sfix19_En23
  input   signed [18:0] coefIn_29;  // sfix19_En23
  input   signed [18:0] coefIn_30;  // sfix19_En23
  input   signed [18:0] coefIn_31;  // sfix19_En23
  input   signed [18:0] coefIn_32;  // sfix19_En23
  input   signed [18:0] coefIn_33;  // sfix19_En23
  input   signed [18:0] coefIn_34;  // sfix19_En23
  input   signed [18:0] coefIn_35;  // sfix19_En23
  input   signed [18:0] coefIn_36;  // sfix19_En23
  input   signed [18:0] coefIn_37;  // sfix19_En23
  input   signed [18:0] coefIn_38;  // sfix19_En23
  input   signed [18:0] coefIn_39;  // sfix19_En23
  input   signed [18:0] coefIn_40;  // sfix19_En23
  input   signed [18:0] coefIn_41;  // sfix19_En23
  input   signed [18:0] coefIn_42;  // sfix19_En23
  input   signed [18:0] coefIn_43;  // sfix19_En23
  input   signed [18:0] coefIn_44;  // sfix19_En23
  input   signed [18:0] coefIn_45;  // sfix19_En23
  input   signed [18:0] coefIn_46;  // sfix19_En23
  input   signed [18:0] coefIn_47;  // sfix19_En23
  input   signed [18:0] coefIn_48;  // sfix19_En23
  input   signed [18:0] coefIn_49;  // sfix19_En23
  input   signed [18:0] coefIn_50;  // sfix19_En23
  input   signed [18:0] coefIn_51;  // sfix19_En23
  input   signed [18:0] coefIn_52;  // sfix19_En23
  input   signed [18:0] coefIn_53;  // sfix19_En23
  input   signed [18:0] coefIn_54;  // sfix19_En23
  input   signed [18:0] coefIn_55;  // sfix19_En23
  input   signed [18:0] coefIn_56;  // sfix19_En23
  input   signed [18:0] coefIn_57;  // sfix19_En23
  input   signed [18:0] coefIn_58;  // sfix19_En23
  input   signed [18:0] coefIn_59;  // sfix19_En23
  input   signed [18:0] coefIn_60;  // sfix19_En23
  input   signed [18:0] coefIn_61;  // sfix19_En23
  input   signed [18:0] coefIn_62;  // sfix19_En23
  input   signed [18:0] coefIn_63;  // sfix19_En23
  input   dinRegVld;
  input   syncReset;
  output  signed [39:0] dout_1_re;  // sfix40_En37
  output  doutVld;


  reg  [0:66] intdelay_reg;  // ufix1 [67]
  wire [0:66] intdelay_reg_next;  // ufix1 [67]
  wire vldShift;
  wire vldOutTmp;
  wire signed [39:0] ZERO_OUT;  // sfix40_En37
  wire signed [39:0] addin;  // sfix40_En37
  wire signed [16:0] dinDly2;  // sfix17_En14
  wire signed [39:0] tapout;  // sfix40_En37
  wire tapoutVld;
  wire signed [16:0] dinDly2_1;  // sfix17_En14
  wire signed [39:0] tapout_1;  // sfix40_En37
  wire tapoutVld_1;
  wire signed [16:0] dinDly2_2;  // sfix17_En14
  wire signed [39:0] tapout_2;  // sfix40_En37
  wire tapoutVld_2;
  wire signed [16:0] dinDly2_3;  // sfix17_En14
  wire signed [39:0] tapout_3;  // sfix40_En37
  wire tapoutVld_3;
  wire signed [16:0] dinDly2_4;  // sfix17_En14
  wire signed [39:0] tapout_4;  // sfix40_En37
  wire tapoutVld_4;
  wire signed [16:0] dinDly2_5;  // sfix17_En14
  wire signed [39:0] tapout_5;  // sfix40_En37
  wire tapoutVld_5;
  wire signed [16:0] dinDly2_6;  // sfix17_En14
  wire signed [39:0] tapout_6;  // sfix40_En37
  wire tapoutVld_6;
  wire signed [16:0] dinDly2_7;  // sfix17_En14
  wire signed [39:0] tapout_7;  // sfix40_En37
  wire tapoutVld_7;
  wire signed [16:0] dinDly2_8;  // sfix17_En14
  wire signed [39:0] tapout_8;  // sfix40_En37
  wire tapoutVld_8;
  wire signed [16:0] dinDly2_9;  // sfix17_En14
  wire signed [39:0] tapout_9;  // sfix40_En37
  wire tapoutVld_9;
  wire signed [16:0] dinDly2_10;  // sfix17_En14
  wire signed [39:0] tapout_10;  // sfix40_En37
  wire tapoutVld_10;
  wire signed [16:0] dinDly2_11;  // sfix17_En14
  wire signed [39:0] tapout_11;  // sfix40_En37
  wire tapoutVld_11;
  wire signed [16:0] dinDly2_12;  // sfix17_En14
  wire signed [39:0] tapout_12;  // sfix40_En37
  wire tapoutVld_12;
  wire signed [16:0] dinDly2_13;  // sfix17_En14
  wire signed [39:0] tapout_13;  // sfix40_En37
  wire tapoutVld_13;
  wire signed [16:0] dinDly2_14;  // sfix17_En14
  wire signed [39:0] tapout_14;  // sfix40_En37
  wire tapoutVld_14;
  wire signed [16:0] dinDly2_15;  // sfix17_En14
  wire signed [39:0] tapout_15;  // sfix40_En37
  wire tapoutVld_15;
  wire signed [16:0] dinDly2_16;  // sfix17_En14
  wire signed [39:0] tapout_16;  // sfix40_En37
  wire tapoutVld_16;
  wire signed [16:0] dinDly2_17;  // sfix17_En14
  wire signed [39:0] tapout_17;  // sfix40_En37
  wire tapoutVld_17;
  wire signed [16:0] dinDly2_18;  // sfix17_En14
  wire signed [39:0] tapout_18;  // sfix40_En37
  wire tapoutVld_18;
  wire signed [16:0] dinDly2_19;  // sfix17_En14
  wire signed [39:0] tapout_19;  // sfix40_En37
  wire tapoutVld_19;
  wire signed [16:0] dinDly2_20;  // sfix17_En14
  wire signed [39:0] tapout_20;  // sfix40_En37
  wire tapoutVld_20;
  wire signed [16:0] dinDly2_21;  // sfix17_En14
  wire signed [39:0] tapout_21;  // sfix40_En37
  wire tapoutVld_21;
  wire signed [16:0] dinDly2_22;  // sfix17_En14
  wire signed [39:0] tapout_22;  // sfix40_En37
  wire tapoutVld_22;
  wire signed [16:0] dinDly2_23;  // sfix17_En14
  wire signed [39:0] tapout_23;  // sfix40_En37
  wire tapoutVld_23;
  wire signed [16:0] dinDly2_24;  // sfix17_En14
  wire signed [39:0] tapout_24;  // sfix40_En37
  wire tapoutVld_24;
  wire signed [16:0] dinDly2_25;  // sfix17_En14
  wire signed [39:0] tapout_25;  // sfix40_En37
  wire tapoutVld_25;
  wire signed [16:0] dinDly2_26;  // sfix17_En14
  wire signed [39:0] tapout_26;  // sfix40_En37
  wire tapoutVld_26;
  wire signed [16:0] dinDly2_27;  // sfix17_En14
  wire signed [39:0] tapout_27;  // sfix40_En37
  wire tapoutVld_27;
  wire signed [16:0] dinDly2_28;  // sfix17_En14
  wire signed [39:0] tapout_28;  // sfix40_En37
  wire tapoutVld_28;
  wire signed [16:0] dinDly2_29;  // sfix17_En14
  wire signed [39:0] tapout_29;  // sfix40_En37
  wire tapoutVld_29;
  wire signed [16:0] dinDly2_30;  // sfix17_En14
  wire signed [39:0] tapout_30;  // sfix40_En37
  wire tapoutVld_30;
  wire signed [16:0] dinDly2_31;  // sfix17_En14
  wire signed [39:0] tapout_31;  // sfix40_En37
  wire tapoutVld_31;
  wire signed [16:0] dinDly2_32;  // sfix17_En14
  wire signed [39:0] tapout_32;  // sfix40_En37
  wire tapoutVld_32;
  wire signed [16:0] dinDly2_33;  // sfix17_En14
  wire signed [39:0] tapout_33;  // sfix40_En37
  wire tapoutVld_33;
  wire signed [16:0] dinDly2_34;  // sfix17_En14
  wire signed [39:0] tapout_34;  // sfix40_En37
  wire tapoutVld_34;
  wire signed [16:0] dinDly2_35;  // sfix17_En14
  wire signed [39:0] tapout_35;  // sfix40_En37
  wire tapoutVld_35;
  wire signed [16:0] dinDly2_36;  // sfix17_En14
  wire signed [39:0] tapout_36;  // sfix40_En37
  wire tapoutVld_36;
  wire signed [16:0] dinDly2_37;  // sfix17_En14
  wire signed [39:0] tapout_37;  // sfix40_En37
  wire tapoutVld_37;
  wire signed [16:0] dinDly2_38;  // sfix17_En14
  wire signed [39:0] tapout_38;  // sfix40_En37
  wire tapoutVld_38;
  wire signed [16:0] dinDly2_39;  // sfix17_En14
  wire signed [39:0] tapout_39;  // sfix40_En37
  wire tapoutVld_39;
  wire signed [16:0] dinDly2_40;  // sfix17_En14
  wire signed [39:0] tapout_40;  // sfix40_En37
  wire tapoutVld_40;
  wire signed [16:0] dinDly2_41;  // sfix17_En14
  wire signed [39:0] tapout_41;  // sfix40_En37
  wire tapoutVld_41;
  wire signed [16:0] dinDly2_42;  // sfix17_En14
  wire signed [39:0] tapout_42;  // sfix40_En37
  wire tapoutVld_42;
  wire signed [16:0] dinDly2_43;  // sfix17_En14
  wire signed [39:0] tapout_43;  // sfix40_En37
  wire tapoutVld_43;
  wire signed [16:0] dinDly2_44;  // sfix17_En14
  wire signed [39:0] tapout_44;  // sfix40_En37
  wire tapoutVld_44;
  wire signed [16:0] dinDly2_45;  // sfix17_En14
  wire signed [39:0] tapout_45;  // sfix40_En37
  wire tapoutVld_45;
  wire signed [16:0] dinDly2_46;  // sfix17_En14
  wire signed [39:0] tapout_46;  // sfix40_En37
  wire tapoutVld_46;
  wire signed [16:0] dinDly2_47;  // sfix17_En14
  wire signed [39:0] tapout_47;  // sfix40_En37
  wire tapoutVld_47;
  wire signed [16:0] dinDly2_48;  // sfix17_En14
  wire signed [39:0] tapout_48;  // sfix40_En37
  wire tapoutVld_48;
  wire signed [16:0] dinDly2_49;  // sfix17_En14
  wire signed [39:0] tapout_49;  // sfix40_En37
  wire tapoutVld_49;
  wire signed [16:0] dinDly2_50;  // sfix17_En14
  wire signed [39:0] tapout_50;  // sfix40_En37
  wire tapoutVld_50;
  wire signed [16:0] dinDly2_51;  // sfix17_En14
  wire signed [39:0] tapout_51;  // sfix40_En37
  wire tapoutVld_51;
  wire signed [16:0] dinDly2_52;  // sfix17_En14
  wire signed [39:0] tapout_52;  // sfix40_En37
  wire tapoutVld_52;
  wire signed [16:0] dinDly2_53;  // sfix17_En14
  wire signed [39:0] tapout_53;  // sfix40_En37
  wire tapoutVld_53;
  wire signed [16:0] dinDly2_54;  // sfix17_En14
  wire signed [39:0] tapout_54;  // sfix40_En37
  wire tapoutVld_54;
  wire signed [16:0] dinDly2_55;  // sfix17_En14
  wire signed [39:0] tapout_55;  // sfix40_En37
  wire tapoutVld_55;
  wire signed [16:0] dinDly2_56;  // sfix17_En14
  wire signed [39:0] tapout_56;  // sfix40_En37
  wire tapoutVld_56;
  wire signed [16:0] dinDly2_57;  // sfix17_En14
  wire signed [39:0] tapout_57;  // sfix40_En37
  wire tapoutVld_57;
  wire signed [16:0] dinDly2_58;  // sfix17_En14
  wire signed [39:0] tapout_58;  // sfix40_En37
  wire tapoutVld_58;
  wire signed [16:0] dinDly2_59;  // sfix17_En14
  wire signed [39:0] tapout_59;  // sfix40_En37
  wire tapoutVld_59;
  wire signed [16:0] dinDly2_60;  // sfix17_En14
  wire signed [39:0] tapout_60;  // sfix40_En37
  wire tapoutVld_60;
  wire signed [16:0] dinDly2_61;  // sfix17_En14
  wire signed [39:0] tapout_61;  // sfix40_En37
  wire tapoutVld_61;
  wire signed [16:0] dinDly2_62;  // sfix17_En14
  wire signed [39:0] tapout_62;  // sfix40_En37
  wire tapoutVld_62;
  wire signed [16:0] dinDly2_63;  // sfix17_En14
  wire signed [39:0] tapout_63;  // sfix40_En37
  wire tapoutVld_63;
  wire signed [39:0] muxOut;  // sfix40_En37
  reg signed [39:0] dout_1_re_1;  // sfix40_En37
  reg  doutVld_1;


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        intdelay_reg[0] <= 1'b0;
        intdelay_reg[1] <= 1'b0;
        intdelay_reg[2] <= 1'b0;
        intdelay_reg[3] <= 1'b0;
        intdelay_reg[4] <= 1'b0;
        intdelay_reg[5] <= 1'b0;
        intdelay_reg[6] <= 1'b0;
        intdelay_reg[7] <= 1'b0;
        intdelay_reg[8] <= 1'b0;
        intdelay_reg[9] <= 1'b0;
        intdelay_reg[10] <= 1'b0;
        intdelay_reg[11] <= 1'b0;
        intdelay_reg[12] <= 1'b0;
        intdelay_reg[13] <= 1'b0;
        intdelay_reg[14] <= 1'b0;
        intdelay_reg[15] <= 1'b0;
        intdelay_reg[16] <= 1'b0;
        intdelay_reg[17] <= 1'b0;
        intdelay_reg[18] <= 1'b0;
        intdelay_reg[19] <= 1'b0;
        intdelay_reg[20] <= 1'b0;
        intdelay_reg[21] <= 1'b0;
        intdelay_reg[22] <= 1'b0;
        intdelay_reg[23] <= 1'b0;
        intdelay_reg[24] <= 1'b0;
        intdelay_reg[25] <= 1'b0;
        intdelay_reg[26] <= 1'b0;
        intdelay_reg[27] <= 1'b0;
        intdelay_reg[28] <= 1'b0;
        intdelay_reg[29] <= 1'b0;
        intdelay_reg[30] <= 1'b0;
        intdelay_reg[31] <= 1'b0;
        intdelay_reg[32] <= 1'b0;
        intdelay_reg[33] <= 1'b0;
        intdelay_reg[34] <= 1'b0;
        intdelay_reg[35] <= 1'b0;
        intdelay_reg[36] <= 1'b0;
        intdelay_reg[37] <= 1'b0;
        intdelay_reg[38] <= 1'b0;
        intdelay_reg[39] <= 1'b0;
        intdelay_reg[40] <= 1'b0;
        intdelay_reg[41] <= 1'b0;
        intdelay_reg[42] <= 1'b0;
        intdelay_reg[43] <= 1'b0;
        intdelay_reg[44] <= 1'b0;
        intdelay_reg[45] <= 1'b0;
        intdelay_reg[46] <= 1'b0;
        intdelay_reg[47] <= 1'b0;
        intdelay_reg[48] <= 1'b0;
        intdelay_reg[49] <= 1'b0;
        intdelay_reg[50] <= 1'b0;
        intdelay_reg[51] <= 1'b0;
        intdelay_reg[52] <= 1'b0;
        intdelay_reg[53] <= 1'b0;
        intdelay_reg[54] <= 1'b0;
        intdelay_reg[55] <= 1'b0;
        intdelay_reg[56] <= 1'b0;
        intdelay_reg[57] <= 1'b0;
        intdelay_reg[58] <= 1'b0;
        intdelay_reg[59] <= 1'b0;
        intdelay_reg[60] <= 1'b0;
        intdelay_reg[61] <= 1'b0;
        intdelay_reg[62] <= 1'b0;
        intdelay_reg[63] <= 1'b0;
        intdelay_reg[64] <= 1'b0;
        intdelay_reg[65] <= 1'b0;
        intdelay_reg[66] <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg[0] <= 1'b0;
            intdelay_reg[1] <= 1'b0;
            intdelay_reg[2] <= 1'b0;
            intdelay_reg[3] <= 1'b0;
            intdelay_reg[4] <= 1'b0;
            intdelay_reg[5] <= 1'b0;
            intdelay_reg[6] <= 1'b0;
            intdelay_reg[7] <= 1'b0;
            intdelay_reg[8] <= 1'b0;
            intdelay_reg[9] <= 1'b0;
            intdelay_reg[10] <= 1'b0;
            intdelay_reg[11] <= 1'b0;
            intdelay_reg[12] <= 1'b0;
            intdelay_reg[13] <= 1'b0;
            intdelay_reg[14] <= 1'b0;
            intdelay_reg[15] <= 1'b0;
            intdelay_reg[16] <= 1'b0;
            intdelay_reg[17] <= 1'b0;
            intdelay_reg[18] <= 1'b0;
            intdelay_reg[19] <= 1'b0;
            intdelay_reg[20] <= 1'b0;
            intdelay_reg[21] <= 1'b0;
            intdelay_reg[22] <= 1'b0;
            intdelay_reg[23] <= 1'b0;
            intdelay_reg[24] <= 1'b0;
            intdelay_reg[25] <= 1'b0;
            intdelay_reg[26] <= 1'b0;
            intdelay_reg[27] <= 1'b0;
            intdelay_reg[28] <= 1'b0;
            intdelay_reg[29] <= 1'b0;
            intdelay_reg[30] <= 1'b0;
            intdelay_reg[31] <= 1'b0;
            intdelay_reg[32] <= 1'b0;
            intdelay_reg[33] <= 1'b0;
            intdelay_reg[34] <= 1'b0;
            intdelay_reg[35] <= 1'b0;
            intdelay_reg[36] <= 1'b0;
            intdelay_reg[37] <= 1'b0;
            intdelay_reg[38] <= 1'b0;
            intdelay_reg[39] <= 1'b0;
            intdelay_reg[40] <= 1'b0;
            intdelay_reg[41] <= 1'b0;
            intdelay_reg[42] <= 1'b0;
            intdelay_reg[43] <= 1'b0;
            intdelay_reg[44] <= 1'b0;
            intdelay_reg[45] <= 1'b0;
            intdelay_reg[46] <= 1'b0;
            intdelay_reg[47] <= 1'b0;
            intdelay_reg[48] <= 1'b0;
            intdelay_reg[49] <= 1'b0;
            intdelay_reg[50] <= 1'b0;
            intdelay_reg[51] <= 1'b0;
            intdelay_reg[52] <= 1'b0;
            intdelay_reg[53] <= 1'b0;
            intdelay_reg[54] <= 1'b0;
            intdelay_reg[55] <= 1'b0;
            intdelay_reg[56] <= 1'b0;
            intdelay_reg[57] <= 1'b0;
            intdelay_reg[58] <= 1'b0;
            intdelay_reg[59] <= 1'b0;
            intdelay_reg[60] <= 1'b0;
            intdelay_reg[61] <= 1'b0;
            intdelay_reg[62] <= 1'b0;
            intdelay_reg[63] <= 1'b0;
            intdelay_reg[64] <= 1'b0;
            intdelay_reg[65] <= 1'b0;
            intdelay_reg[66] <= 1'b0;
          end
          else begin
            if (dinRegVld) begin
              intdelay_reg[0] <= intdelay_reg_next[0];
              intdelay_reg[1] <= intdelay_reg_next[1];
              intdelay_reg[2] <= intdelay_reg_next[2];
              intdelay_reg[3] <= intdelay_reg_next[3];
              intdelay_reg[4] <= intdelay_reg_next[4];
              intdelay_reg[5] <= intdelay_reg_next[5];
              intdelay_reg[6] <= intdelay_reg_next[6];
              intdelay_reg[7] <= intdelay_reg_next[7];
              intdelay_reg[8] <= intdelay_reg_next[8];
              intdelay_reg[9] <= intdelay_reg_next[9];
              intdelay_reg[10] <= intdelay_reg_next[10];
              intdelay_reg[11] <= intdelay_reg_next[11];
              intdelay_reg[12] <= intdelay_reg_next[12];
              intdelay_reg[13] <= intdelay_reg_next[13];
              intdelay_reg[14] <= intdelay_reg_next[14];
              intdelay_reg[15] <= intdelay_reg_next[15];
              intdelay_reg[16] <= intdelay_reg_next[16];
              intdelay_reg[17] <= intdelay_reg_next[17];
              intdelay_reg[18] <= intdelay_reg_next[18];
              intdelay_reg[19] <= intdelay_reg_next[19];
              intdelay_reg[20] <= intdelay_reg_next[20];
              intdelay_reg[21] <= intdelay_reg_next[21];
              intdelay_reg[22] <= intdelay_reg_next[22];
              intdelay_reg[23] <= intdelay_reg_next[23];
              intdelay_reg[24] <= intdelay_reg_next[24];
              intdelay_reg[25] <= intdelay_reg_next[25];
              intdelay_reg[26] <= intdelay_reg_next[26];
              intdelay_reg[27] <= intdelay_reg_next[27];
              intdelay_reg[28] <= intdelay_reg_next[28];
              intdelay_reg[29] <= intdelay_reg_next[29];
              intdelay_reg[30] <= intdelay_reg_next[30];
              intdelay_reg[31] <= intdelay_reg_next[31];
              intdelay_reg[32] <= intdelay_reg_next[32];
              intdelay_reg[33] <= intdelay_reg_next[33];
              intdelay_reg[34] <= intdelay_reg_next[34];
              intdelay_reg[35] <= intdelay_reg_next[35];
              intdelay_reg[36] <= intdelay_reg_next[36];
              intdelay_reg[37] <= intdelay_reg_next[37];
              intdelay_reg[38] <= intdelay_reg_next[38];
              intdelay_reg[39] <= intdelay_reg_next[39];
              intdelay_reg[40] <= intdelay_reg_next[40];
              intdelay_reg[41] <= intdelay_reg_next[41];
              intdelay_reg[42] <= intdelay_reg_next[42];
              intdelay_reg[43] <= intdelay_reg_next[43];
              intdelay_reg[44] <= intdelay_reg_next[44];
              intdelay_reg[45] <= intdelay_reg_next[45];
              intdelay_reg[46] <= intdelay_reg_next[46];
              intdelay_reg[47] <= intdelay_reg_next[47];
              intdelay_reg[48] <= intdelay_reg_next[48];
              intdelay_reg[49] <= intdelay_reg_next[49];
              intdelay_reg[50] <= intdelay_reg_next[50];
              intdelay_reg[51] <= intdelay_reg_next[51];
              intdelay_reg[52] <= intdelay_reg_next[52];
              intdelay_reg[53] <= intdelay_reg_next[53];
              intdelay_reg[54] <= intdelay_reg_next[54];
              intdelay_reg[55] <= intdelay_reg_next[55];
              intdelay_reg[56] <= intdelay_reg_next[56];
              intdelay_reg[57] <= intdelay_reg_next[57];
              intdelay_reg[58] <= intdelay_reg_next[58];
              intdelay_reg[59] <= intdelay_reg_next[59];
              intdelay_reg[60] <= intdelay_reg_next[60];
              intdelay_reg[61] <= intdelay_reg_next[61];
              intdelay_reg[62] <= intdelay_reg_next[62];
              intdelay_reg[63] <= intdelay_reg_next[63];
              intdelay_reg[64] <= intdelay_reg_next[64];
              intdelay_reg[65] <= intdelay_reg_next[65];
              intdelay_reg[66] <= intdelay_reg_next[66];
            end
          end
        end
      end
    end

  assign vldShift = intdelay_reg[66];
  assign intdelay_reg_next[0] = dinRegVld;
  assign intdelay_reg_next[1] = intdelay_reg[0];
  assign intdelay_reg_next[2] = intdelay_reg[1];
  assign intdelay_reg_next[3] = intdelay_reg[2];
  assign intdelay_reg_next[4] = intdelay_reg[3];
  assign intdelay_reg_next[5] = intdelay_reg[4];
  assign intdelay_reg_next[6] = intdelay_reg[5];
  assign intdelay_reg_next[7] = intdelay_reg[6];
  assign intdelay_reg_next[8] = intdelay_reg[7];
  assign intdelay_reg_next[9] = intdelay_reg[8];
  assign intdelay_reg_next[10] = intdelay_reg[9];
  assign intdelay_reg_next[11] = intdelay_reg[10];
  assign intdelay_reg_next[12] = intdelay_reg[11];
  assign intdelay_reg_next[13] = intdelay_reg[12];
  assign intdelay_reg_next[14] = intdelay_reg[13];
  assign intdelay_reg_next[15] = intdelay_reg[14];
  assign intdelay_reg_next[16] = intdelay_reg[15];
  assign intdelay_reg_next[17] = intdelay_reg[16];
  assign intdelay_reg_next[18] = intdelay_reg[17];
  assign intdelay_reg_next[19] = intdelay_reg[18];
  assign intdelay_reg_next[20] = intdelay_reg[19];
  assign intdelay_reg_next[21] = intdelay_reg[20];
  assign intdelay_reg_next[22] = intdelay_reg[21];
  assign intdelay_reg_next[23] = intdelay_reg[22];
  assign intdelay_reg_next[24] = intdelay_reg[23];
  assign intdelay_reg_next[25] = intdelay_reg[24];
  assign intdelay_reg_next[26] = intdelay_reg[25];
  assign intdelay_reg_next[27] = intdelay_reg[26];
  assign intdelay_reg_next[28] = intdelay_reg[27];
  assign intdelay_reg_next[29] = intdelay_reg[28];
  assign intdelay_reg_next[30] = intdelay_reg[29];
  assign intdelay_reg_next[31] = intdelay_reg[30];
  assign intdelay_reg_next[32] = intdelay_reg[31];
  assign intdelay_reg_next[33] = intdelay_reg[32];
  assign intdelay_reg_next[34] = intdelay_reg[33];
  assign intdelay_reg_next[35] = intdelay_reg[34];
  assign intdelay_reg_next[36] = intdelay_reg[35];
  assign intdelay_reg_next[37] = intdelay_reg[36];
  assign intdelay_reg_next[38] = intdelay_reg[37];
  assign intdelay_reg_next[39] = intdelay_reg[38];
  assign intdelay_reg_next[40] = intdelay_reg[39];
  assign intdelay_reg_next[41] = intdelay_reg[40];
  assign intdelay_reg_next[42] = intdelay_reg[41];
  assign intdelay_reg_next[43] = intdelay_reg[42];
  assign intdelay_reg_next[44] = intdelay_reg[43];
  assign intdelay_reg_next[45] = intdelay_reg[44];
  assign intdelay_reg_next[46] = intdelay_reg[45];
  assign intdelay_reg_next[47] = intdelay_reg[46];
  assign intdelay_reg_next[48] = intdelay_reg[47];
  assign intdelay_reg_next[49] = intdelay_reg[48];
  assign intdelay_reg_next[50] = intdelay_reg[49];
  assign intdelay_reg_next[51] = intdelay_reg[50];
  assign intdelay_reg_next[52] = intdelay_reg[51];
  assign intdelay_reg_next[53] = intdelay_reg[52];
  assign intdelay_reg_next[54] = intdelay_reg[53];
  assign intdelay_reg_next[55] = intdelay_reg[54];
  assign intdelay_reg_next[56] = intdelay_reg[55];
  assign intdelay_reg_next[57] = intdelay_reg[56];
  assign intdelay_reg_next[58] = intdelay_reg[57];
  assign intdelay_reg_next[59] = intdelay_reg[58];
  assign intdelay_reg_next[60] = intdelay_reg[59];
  assign intdelay_reg_next[61] = intdelay_reg[60];
  assign intdelay_reg_next[62] = intdelay_reg[61];
  assign intdelay_reg_next[63] = intdelay_reg[62];
  assign intdelay_reg_next[64] = intdelay_reg[63];
  assign intdelay_reg_next[65] = intdelay_reg[64];
  assign intdelay_reg_next[66] = intdelay_reg[65];



  assign vldOutTmp = dinRegVld & vldShift;



  assign ZERO_OUT = 40'sh0000000000;



  assign addin = 40'sh0000000000;



  FilterTapSystolicWvldin u_FilterTap_1 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinReg2_0_re),  // sfix17_En14
                                         .coefIn_0(coefIn_0),  // sfix19_En23
                                         .addin(addin),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2),  // sfix17_En14
                                         .tapout(tapout),  // sfix40_En37
                                         .tapoutVld(tapoutVld)
                                         );

  FilterTapSystolicWvldin u_FilterTap_2 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinDly2),  // sfix17_En14
                                         .coefIn_0(coefIn_1),  // sfix19_En23
                                         .addin(tapout),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_1),  // sfix17_En14
                                         .tapout(tapout_1),  // sfix40_En37
                                         .tapoutVld(tapoutVld_1)
                                         );

  FilterTapSystolicWvldin u_FilterTap_3 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinDly2_1),  // sfix17_En14
                                         .coefIn_0(coefIn_2),  // sfix19_En23
                                         .addin(tapout_1),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_2),  // sfix17_En14
                                         .tapout(tapout_2),  // sfix40_En37
                                         .tapoutVld(tapoutVld_2)
                                         );

  FilterTapSystolicWvldin u_FilterTap_4 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinDly2_2),  // sfix17_En14
                                         .coefIn_0(coefIn_3),  // sfix19_En23
                                         .addin(tapout_2),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_3),  // sfix17_En14
                                         .tapout(tapout_3),  // sfix40_En37
                                         .tapoutVld(tapoutVld_3)
                                         );

  FilterTapSystolicWvldin u_FilterTap_5 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinDly2_3),  // sfix17_En14
                                         .coefIn_0(coefIn_4),  // sfix19_En23
                                         .addin(tapout_3),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_4),  // sfix17_En14
                                         .tapout(tapout_4),  // sfix40_En37
                                         .tapoutVld(tapoutVld_4)
                                         );

  FilterTapSystolicWvldin u_FilterTap_6 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinDly2_4),  // sfix17_En14
                                         .coefIn_0(coefIn_5),  // sfix19_En23
                                         .addin(tapout_4),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_5),  // sfix17_En14
                                         .tapout(tapout_5),  // sfix40_En37
                                         .tapoutVld(tapoutVld_5)
                                         );

  FilterTapSystolicWvldin u_FilterTap_7 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinDly2_5),  // sfix17_En14
                                         .coefIn_0(coefIn_6),  // sfix19_En23
                                         .addin(tapout_5),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_6),  // sfix17_En14
                                         .tapout(tapout_6),  // sfix40_En37
                                         .tapoutVld(tapoutVld_6)
                                         );

  FilterTapSystolicWvldin u_FilterTap_8 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinDly2_6),  // sfix17_En14
                                         .coefIn_0(coefIn_7),  // sfix19_En23
                                         .addin(tapout_6),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_7),  // sfix17_En14
                                         .tapout(tapout_7),  // sfix40_En37
                                         .tapoutVld(tapoutVld_7)
                                         );

  FilterTapSystolicWvldin u_FilterTap_9 (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .dinReg2_0_re(dinDly2_7),  // sfix17_En14
                                         .coefIn_0(coefIn_8),  // sfix19_En23
                                         .addin(tapout_7),  // sfix40_En37
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_8),  // sfix17_En14
                                         .tapout(tapout_8),  // sfix40_En37
                                         .tapoutVld(tapoutVld_8)
                                         );

  FilterTapSystolicWvldin u_FilterTap_10 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_8),  // sfix17_En14
                                          .coefIn_0(coefIn_9),  // sfix19_En23
                                          .addin(tapout_8),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_9),  // sfix17_En14
                                          .tapout(tapout_9),  // sfix40_En37
                                          .tapoutVld(tapoutVld_9)
                                          );

  FilterTapSystolicWvldin u_FilterTap_11 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_9),  // sfix17_En14
                                          .coefIn_0(coefIn_10),  // sfix19_En23
                                          .addin(tapout_9),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_10),  // sfix17_En14
                                          .tapout(tapout_10),  // sfix40_En37
                                          .tapoutVld(tapoutVld_10)
                                          );

  FilterTapSystolicWvldin u_FilterTap_12 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_10),  // sfix17_En14
                                          .coefIn_0(coefIn_11),  // sfix19_En23
                                          .addin(tapout_10),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_11),  // sfix17_En14
                                          .tapout(tapout_11),  // sfix40_En37
                                          .tapoutVld(tapoutVld_11)
                                          );

  FilterTapSystolicWvldin u_FilterTap_13 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_11),  // sfix17_En14
                                          .coefIn_0(coefIn_12),  // sfix19_En23
                                          .addin(tapout_11),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_12),  // sfix17_En14
                                          .tapout(tapout_12),  // sfix40_En37
                                          .tapoutVld(tapoutVld_12)
                                          );

  FilterTapSystolicWvldin u_FilterTap_14 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_12),  // sfix17_En14
                                          .coefIn_0(coefIn_13),  // sfix19_En23
                                          .addin(tapout_12),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_13),  // sfix17_En14
                                          .tapout(tapout_13),  // sfix40_En37
                                          .tapoutVld(tapoutVld_13)
                                          );

  FilterTapSystolicWvldin u_FilterTap_15 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_13),  // sfix17_En14
                                          .coefIn_0(coefIn_14),  // sfix19_En23
                                          .addin(tapout_13),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_14),  // sfix17_En14
                                          .tapout(tapout_14),  // sfix40_En37
                                          .tapoutVld(tapoutVld_14)
                                          );

  FilterTapSystolicWvldin u_FilterTap_16 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_14),  // sfix17_En14
                                          .coefIn_0(coefIn_15),  // sfix19_En23
                                          .addin(tapout_14),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_15),  // sfix17_En14
                                          .tapout(tapout_15),  // sfix40_En37
                                          .tapoutVld(tapoutVld_15)
                                          );

  FilterTapSystolicWvldin u_FilterTap_17 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_15),  // sfix17_En14
                                          .coefIn_0(coefIn_16),  // sfix19_En23
                                          .addin(tapout_15),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_16),  // sfix17_En14
                                          .tapout(tapout_16),  // sfix40_En37
                                          .tapoutVld(tapoutVld_16)
                                          );

  FilterTapSystolicWvldin u_FilterTap_18 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_16),  // sfix17_En14
                                          .coefIn_0(coefIn_17),  // sfix19_En23
                                          .addin(tapout_16),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_17),  // sfix17_En14
                                          .tapout(tapout_17),  // sfix40_En37
                                          .tapoutVld(tapoutVld_17)
                                          );

  FilterTapSystolicWvldin u_FilterTap_19 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_17),  // sfix17_En14
                                          .coefIn_0(coefIn_18),  // sfix19_En23
                                          .addin(tapout_17),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_18),  // sfix17_En14
                                          .tapout(tapout_18),  // sfix40_En37
                                          .tapoutVld(tapoutVld_18)
                                          );

  FilterTapSystolicWvldin u_FilterTap_20 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_18),  // sfix17_En14
                                          .coefIn_0(coefIn_19),  // sfix19_En23
                                          .addin(tapout_18),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_19),  // sfix17_En14
                                          .tapout(tapout_19),  // sfix40_En37
                                          .tapoutVld(tapoutVld_19)
                                          );

  FilterTapSystolicWvldin u_FilterTap_21 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_19),  // sfix17_En14
                                          .coefIn_0(coefIn_20),  // sfix19_En23
                                          .addin(tapout_19),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_20),  // sfix17_En14
                                          .tapout(tapout_20),  // sfix40_En37
                                          .tapoutVld(tapoutVld_20)
                                          );

  FilterTapSystolicWvldin u_FilterTap_22 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_20),  // sfix17_En14
                                          .coefIn_0(coefIn_21),  // sfix19_En23
                                          .addin(tapout_20),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_21),  // sfix17_En14
                                          .tapout(tapout_21),  // sfix40_En37
                                          .tapoutVld(tapoutVld_21)
                                          );

  FilterTapSystolicWvldin u_FilterTap_23 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_21),  // sfix17_En14
                                          .coefIn_0(coefIn_22),  // sfix19_En23
                                          .addin(tapout_21),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_22),  // sfix17_En14
                                          .tapout(tapout_22),  // sfix40_En37
                                          .tapoutVld(tapoutVld_22)
                                          );

  FilterTapSystolicWvldin u_FilterTap_24 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_22),  // sfix17_En14
                                          .coefIn_0(coefIn_23),  // sfix19_En23
                                          .addin(tapout_22),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_23),  // sfix17_En14
                                          .tapout(tapout_23),  // sfix40_En37
                                          .tapoutVld(tapoutVld_23)
                                          );

  FilterTapSystolicWvldin u_FilterTap_25 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_23),  // sfix17_En14
                                          .coefIn_0(coefIn_24),  // sfix19_En23
                                          .addin(tapout_23),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_24),  // sfix17_En14
                                          .tapout(tapout_24),  // sfix40_En37
                                          .tapoutVld(tapoutVld_24)
                                          );

  FilterTapSystolicWvldin u_FilterTap_26 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_24),  // sfix17_En14
                                          .coefIn_0(coefIn_25),  // sfix19_En23
                                          .addin(tapout_24),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_25),  // sfix17_En14
                                          .tapout(tapout_25),  // sfix40_En37
                                          .tapoutVld(tapoutVld_25)
                                          );

  FilterTapSystolicWvldin u_FilterTap_27 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_25),  // sfix17_En14
                                          .coefIn_0(coefIn_26),  // sfix19_En23
                                          .addin(tapout_25),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_26),  // sfix17_En14
                                          .tapout(tapout_26),  // sfix40_En37
                                          .tapoutVld(tapoutVld_26)
                                          );

  FilterTapSystolicWvldin u_FilterTap_28 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_26),  // sfix17_En14
                                          .coefIn_0(coefIn_27),  // sfix19_En23
                                          .addin(tapout_26),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_27),  // sfix17_En14
                                          .tapout(tapout_27),  // sfix40_En37
                                          .tapoutVld(tapoutVld_27)
                                          );

  FilterTapSystolicWvldin u_FilterTap_29 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_27),  // sfix17_En14
                                          .coefIn_0(coefIn_28),  // sfix19_En23
                                          .addin(tapout_27),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_28),  // sfix17_En14
                                          .tapout(tapout_28),  // sfix40_En37
                                          .tapoutVld(tapoutVld_28)
                                          );

  FilterTapSystolicWvldin u_FilterTap_30 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_28),  // sfix17_En14
                                          .coefIn_0(coefIn_29),  // sfix19_En23
                                          .addin(tapout_28),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_29),  // sfix17_En14
                                          .tapout(tapout_29),  // sfix40_En37
                                          .tapoutVld(tapoutVld_29)
                                          );

  FilterTapSystolicWvldin u_FilterTap_31 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_29),  // sfix17_En14
                                          .coefIn_0(coefIn_30),  // sfix19_En23
                                          .addin(tapout_29),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_30),  // sfix17_En14
                                          .tapout(tapout_30),  // sfix40_En37
                                          .tapoutVld(tapoutVld_30)
                                          );

  FilterTapSystolicWvldin u_FilterTap_32 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_30),  // sfix17_En14
                                          .coefIn_0(coefIn_31),  // sfix19_En23
                                          .addin(tapout_30),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_31),  // sfix17_En14
                                          .tapout(tapout_31),  // sfix40_En37
                                          .tapoutVld(tapoutVld_31)
                                          );

  FilterTapSystolicWvldin u_FilterTap_33 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_31),  // sfix17_En14
                                          .coefIn_0(coefIn_32),  // sfix19_En23
                                          .addin(tapout_31),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_32),  // sfix17_En14
                                          .tapout(tapout_32),  // sfix40_En37
                                          .tapoutVld(tapoutVld_32)
                                          );

  FilterTapSystolicWvldin u_FilterTap_34 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_32),  // sfix17_En14
                                          .coefIn_0(coefIn_33),  // sfix19_En23
                                          .addin(tapout_32),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_33),  // sfix17_En14
                                          .tapout(tapout_33),  // sfix40_En37
                                          .tapoutVld(tapoutVld_33)
                                          );

  FilterTapSystolicWvldin u_FilterTap_35 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_33),  // sfix17_En14
                                          .coefIn_0(coefIn_34),  // sfix19_En23
                                          .addin(tapout_33),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_34),  // sfix17_En14
                                          .tapout(tapout_34),  // sfix40_En37
                                          .tapoutVld(tapoutVld_34)
                                          );

  FilterTapSystolicWvldin u_FilterTap_36 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_34),  // sfix17_En14
                                          .coefIn_0(coefIn_35),  // sfix19_En23
                                          .addin(tapout_34),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_35),  // sfix17_En14
                                          .tapout(tapout_35),  // sfix40_En37
                                          .tapoutVld(tapoutVld_35)
                                          );

  FilterTapSystolicWvldin u_FilterTap_37 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_35),  // sfix17_En14
                                          .coefIn_0(coefIn_36),  // sfix19_En23
                                          .addin(tapout_35),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_36),  // sfix17_En14
                                          .tapout(tapout_36),  // sfix40_En37
                                          .tapoutVld(tapoutVld_36)
                                          );

  FilterTapSystolicWvldin u_FilterTap_38 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_36),  // sfix17_En14
                                          .coefIn_0(coefIn_37),  // sfix19_En23
                                          .addin(tapout_36),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_37),  // sfix17_En14
                                          .tapout(tapout_37),  // sfix40_En37
                                          .tapoutVld(tapoutVld_37)
                                          );

  FilterTapSystolicWvldin u_FilterTap_39 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_37),  // sfix17_En14
                                          .coefIn_0(coefIn_38),  // sfix19_En23
                                          .addin(tapout_37),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_38),  // sfix17_En14
                                          .tapout(tapout_38),  // sfix40_En37
                                          .tapoutVld(tapoutVld_38)
                                          );

  FilterTapSystolicWvldin u_FilterTap_40 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_38),  // sfix17_En14
                                          .coefIn_0(coefIn_39),  // sfix19_En23
                                          .addin(tapout_38),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_39),  // sfix17_En14
                                          .tapout(tapout_39),  // sfix40_En37
                                          .tapoutVld(tapoutVld_39)
                                          );

  FilterTapSystolicWvldin u_FilterTap_41 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_39),  // sfix17_En14
                                          .coefIn_0(coefIn_40),  // sfix19_En23
                                          .addin(tapout_39),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_40),  // sfix17_En14
                                          .tapout(tapout_40),  // sfix40_En37
                                          .tapoutVld(tapoutVld_40)
                                          );

  FilterTapSystolicWvldin u_FilterTap_42 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_40),  // sfix17_En14
                                          .coefIn_0(coefIn_41),  // sfix19_En23
                                          .addin(tapout_40),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_41),  // sfix17_En14
                                          .tapout(tapout_41),  // sfix40_En37
                                          .tapoutVld(tapoutVld_41)
                                          );

  FilterTapSystolicWvldin u_FilterTap_43 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_41),  // sfix17_En14
                                          .coefIn_0(coefIn_42),  // sfix19_En23
                                          .addin(tapout_41),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_42),  // sfix17_En14
                                          .tapout(tapout_42),  // sfix40_En37
                                          .tapoutVld(tapoutVld_42)
                                          );

  FilterTapSystolicWvldin u_FilterTap_44 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_42),  // sfix17_En14
                                          .coefIn_0(coefIn_43),  // sfix19_En23
                                          .addin(tapout_42),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_43),  // sfix17_En14
                                          .tapout(tapout_43),  // sfix40_En37
                                          .tapoutVld(tapoutVld_43)
                                          );

  FilterTapSystolicWvldin u_FilterTap_45 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_43),  // sfix17_En14
                                          .coefIn_0(coefIn_44),  // sfix19_En23
                                          .addin(tapout_43),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_44),  // sfix17_En14
                                          .tapout(tapout_44),  // sfix40_En37
                                          .tapoutVld(tapoutVld_44)
                                          );

  FilterTapSystolicWvldin u_FilterTap_46 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_44),  // sfix17_En14
                                          .coefIn_0(coefIn_45),  // sfix19_En23
                                          .addin(tapout_44),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_45),  // sfix17_En14
                                          .tapout(tapout_45),  // sfix40_En37
                                          .tapoutVld(tapoutVld_45)
                                          );

  FilterTapSystolicWvldin u_FilterTap_47 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_45),  // sfix17_En14
                                          .coefIn_0(coefIn_46),  // sfix19_En23
                                          .addin(tapout_45),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_46),  // sfix17_En14
                                          .tapout(tapout_46),  // sfix40_En37
                                          .tapoutVld(tapoutVld_46)
                                          );

  FilterTapSystolicWvldin u_FilterTap_48 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_46),  // sfix17_En14
                                          .coefIn_0(coefIn_47),  // sfix19_En23
                                          .addin(tapout_46),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_47),  // sfix17_En14
                                          .tapout(tapout_47),  // sfix40_En37
                                          .tapoutVld(tapoutVld_47)
                                          );

  FilterTapSystolicWvldin u_FilterTap_49 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_47),  // sfix17_En14
                                          .coefIn_0(coefIn_48),  // sfix19_En23
                                          .addin(tapout_47),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_48),  // sfix17_En14
                                          .tapout(tapout_48),  // sfix40_En37
                                          .tapoutVld(tapoutVld_48)
                                          );

  FilterTapSystolicWvldin u_FilterTap_50 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_48),  // sfix17_En14
                                          .coefIn_0(coefIn_49),  // sfix19_En23
                                          .addin(tapout_48),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_49),  // sfix17_En14
                                          .tapout(tapout_49),  // sfix40_En37
                                          .tapoutVld(tapoutVld_49)
                                          );

  FilterTapSystolicWvldin u_FilterTap_51 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_49),  // sfix17_En14
                                          .coefIn_0(coefIn_50),  // sfix19_En23
                                          .addin(tapout_49),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_50),  // sfix17_En14
                                          .tapout(tapout_50),  // sfix40_En37
                                          .tapoutVld(tapoutVld_50)
                                          );

  FilterTapSystolicWvldin u_FilterTap_52 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_50),  // sfix17_En14
                                          .coefIn_0(coefIn_51),  // sfix19_En23
                                          .addin(tapout_50),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_51),  // sfix17_En14
                                          .tapout(tapout_51),  // sfix40_En37
                                          .tapoutVld(tapoutVld_51)
                                          );

  FilterTapSystolicWvldin u_FilterTap_53 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_51),  // sfix17_En14
                                          .coefIn_0(coefIn_52),  // sfix19_En23
                                          .addin(tapout_51),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_52),  // sfix17_En14
                                          .tapout(tapout_52),  // sfix40_En37
                                          .tapoutVld(tapoutVld_52)
                                          );

  FilterTapSystolicWvldin u_FilterTap_54 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_52),  // sfix17_En14
                                          .coefIn_0(coefIn_53),  // sfix19_En23
                                          .addin(tapout_52),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_53),  // sfix17_En14
                                          .tapout(tapout_53),  // sfix40_En37
                                          .tapoutVld(tapoutVld_53)
                                          );

  FilterTapSystolicWvldin u_FilterTap_55 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_53),  // sfix17_En14
                                          .coefIn_0(coefIn_54),  // sfix19_En23
                                          .addin(tapout_53),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_54),  // sfix17_En14
                                          .tapout(tapout_54),  // sfix40_En37
                                          .tapoutVld(tapoutVld_54)
                                          );

  FilterTapSystolicWvldin u_FilterTap_56 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_54),  // sfix17_En14
                                          .coefIn_0(coefIn_55),  // sfix19_En23
                                          .addin(tapout_54),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_55),  // sfix17_En14
                                          .tapout(tapout_55),  // sfix40_En37
                                          .tapoutVld(tapoutVld_55)
                                          );

  FilterTapSystolicWvldin u_FilterTap_57 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_55),  // sfix17_En14
                                          .coefIn_0(coefIn_56),  // sfix19_En23
                                          .addin(tapout_55),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_56),  // sfix17_En14
                                          .tapout(tapout_56),  // sfix40_En37
                                          .tapoutVld(tapoutVld_56)
                                          );

  FilterTapSystolicWvldin u_FilterTap_58 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_56),  // sfix17_En14
                                          .coefIn_0(coefIn_57),  // sfix19_En23
                                          .addin(tapout_56),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_57),  // sfix17_En14
                                          .tapout(tapout_57),  // sfix40_En37
                                          .tapoutVld(tapoutVld_57)
                                          );

  FilterTapSystolicWvldin u_FilterTap_59 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_57),  // sfix17_En14
                                          .coefIn_0(coefIn_58),  // sfix19_En23
                                          .addin(tapout_57),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_58),  // sfix17_En14
                                          .tapout(tapout_58),  // sfix40_En37
                                          .tapoutVld(tapoutVld_58)
                                          );

  FilterTapSystolicWvldin u_FilterTap_60 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_58),  // sfix17_En14
                                          .coefIn_0(coefIn_59),  // sfix19_En23
                                          .addin(tapout_58),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_59),  // sfix17_En14
                                          .tapout(tapout_59),  // sfix40_En37
                                          .tapoutVld(tapoutVld_59)
                                          );

  FilterTapSystolicWvldin u_FilterTap_61 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_59),  // sfix17_En14
                                          .coefIn_0(coefIn_60),  // sfix19_En23
                                          .addin(tapout_59),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_60),  // sfix17_En14
                                          .tapout(tapout_60),  // sfix40_En37
                                          .tapoutVld(tapoutVld_60)
                                          );

  FilterTapSystolicWvldin u_FilterTap_62 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_60),  // sfix17_En14
                                          .coefIn_0(coefIn_61),  // sfix19_En23
                                          .addin(tapout_60),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_61),  // sfix17_En14
                                          .tapout(tapout_61),  // sfix40_En37
                                          .tapoutVld(tapoutVld_61)
                                          );

  FilterTapSystolicWvldin u_FilterTap_63 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_61),  // sfix17_En14
                                          .coefIn_0(coefIn_62),  // sfix19_En23
                                          .addin(tapout_61),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_62),  // sfix17_En14
                                          .tapout(tapout_62),  // sfix40_En37
                                          .tapoutVld(tapoutVld_62)
                                          );

  FilterTapSystolicWvldin u_FilterTap_64 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dinReg2_0_re(dinDly2_62),  // sfix17_En14
                                          .coefIn_0(coefIn_63),  // sfix19_En23
                                          .addin(tapout_62),  // sfix40_En37
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_63),  // sfix17_En14
                                          .tapout(tapout_63),  // sfix40_En37
                                          .tapoutVld(tapoutVld_63)
                                          );

  assign muxOut = (vldOutTmp == 1'b0 ? ZERO_OUT :
              tapout_63);



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dout_1_re_1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 40'sh0000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        doutVld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            doutVld_1 <= 1'b0;
          end
          else begin
            doutVld_1 <= vldOutTmp;
          end
        end
      end
    end



  assign dout_1_re = dout_1_re_1;

  assign doutVld = doutVld_1;

endmodule  // subFilter

