-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\project_detect\Discrete_FIR_Filter_HDL_Optimized.vhd
-- Created: 2021-02-13 15:14:38
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_FIR_Filter_HDL_Optimized
-- Source Path: project_detect/Pulse Detector/Discrete FIR Filter HDL Optimized
-- Hierarchy Level: 1
-- 
-- Discrete FIR Filter HDL Optimized
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Discrete_FIR_Filter_HDL_Optimized IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataIn_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(39 DOWNTO 0);  -- sfix40_En37
        dataOut_im                        :   OUT   std_logic_vector(39 DOWNTO 0);  -- sfix40_En37
        validOut                          :   OUT   std_logic
        );
END Discrete_FIR_Filter_HDL_Optimized;


ARCHITECTURE rtl OF Discrete_FIR_Filter_HDL_Optimized IS

  -- Component Declarations
  COMPONENT FilterBank
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(39 DOWNTO 0);  -- sfix40_En37
          dataOut_im                      :   OUT   std_logic_vector(39 DOWNTO 0);  -- sfix40_En37
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterBank
    USE ENTITY work.FilterBank(rtl);

  -- Signals
  SIGNAL dataOut_re_tmp                   : std_logic_vector(39 DOWNTO 0);  -- ufix40
  SIGNAL dataOut_im_tmp                   : std_logic_vector(39 DOWNTO 0);  -- ufix40

BEGIN
  u_FilterBank : FilterBank
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn_re => dataIn_re,  -- sfix16_En14
              dataIn_im => dataIn_im,  -- sfix16_En14
              validIn => validIn,
              dataOut_re => dataOut_re_tmp,  -- sfix40_En37
              dataOut_im => dataOut_im_tmp,  -- sfix40_En37
              validOut => validOut
              );

  dataOut_re <= dataOut_re_tmp;

  dataOut_im <= dataOut_im_tmp;

END rtl;

