-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\project_detect\Pulse_Detector_pkg.vhd
-- Created: 2021-02-13 15:14:38
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Pulse_Detector_pkg IS
  TYPE vector_of_std_logic_vector18 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(17 DOWNTO 0);
  TYPE vector_of_signed18 IS ARRAY (NATURAL RANGE <>) OF signed(17 DOWNTO 0);
  TYPE vector_of_signed19 IS ARRAY (NATURAL RANGE <>) OF signed(18 DOWNTO 0);
  TYPE vector_of_std_logic_vector19 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(18 DOWNTO 0);
END Pulse_Detector_pkg;

