% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name ham
%  @associatedFile /MATLAB Drive/ham.m
%  @mostRecentlyActioned true
%  @uniqueId 6667D609

ham.m

%% @name ham_2
%  @associatedFile /MATLAB Drive/ham.m
%  @mostRecentlyActioned false
%  @uniqueId 76122D26

ham

%% @name hamming
%  @associatedFile /MATLAB Drive/hamming.m
%  @mostRecentlyActioned true
%  @uniqueId AA54A9B1

hamming

%% @name hamm
%  @associatedFile /MATLAB Drive/hamm.m
%  @mostRecentlyActioned true
%  @uniqueId 440CD857

hamm

%% @name biterror
%  @associatedFile /MATLAB Drive/biterror.m
%  @mostRecentlyActioned true
%  @uniqueId CE614019

biterror

%% @name photo
%  @associatedFile /MATLAB Drive/photo.m
%  @mostRecentlyActioned true
%  @uniqueId 99FA2681

photo

%% @name MainCode
%  @associatedFile /MATLAB Drive/MainCode.m
%  @mostRecentlyActioned true
%  @uniqueId BB2EBAA2

MainCode

%% @name colordetection
%  @associatedFile /MATLAB Drive/images/colordetection.m
%  @mostRecentlyActioned true
%  @uniqueId 01B650E9

colordetection

%% @name diffractionlong
%  @associatedFile /MATLAB Drive/diffractionlong.m
%  @mostRecentlyActioned true
%  @uniqueId 0A8D97E2

diffractionlong

%% @name ecg
%  @associatedFile /MATLAB Drive/images/ecg.m
%  @mostRecentlyActioned true
%  @uniqueId 7A3396C3

ecg

%% @name exp61
%  @associatedFile /MATLAB Drive/exp61.m
%  @mostRecentlyActioned true
%  @uniqueId 33E0BB89

exp61

